#!/usr/bin/env python3
"""Browser-based live preview server for a LaTeX document.

Generated by the `latex_serve_web` Bazel rule. Don't edit by hand;
edit //latex/private:serve_web.py.tpl instead.

What this is:

* A tiny HTTP server (Python stdlib's http.server) running on
  localhost.
* GET /          -> a single-page HTML wrapper that loads PDF.js from
                    a CDN, renders the current PDF in a canvas, and
                    listens for reload events on /events.
* GET /pdf       -> serves the bytes of bazel-bin/<doc>.pdf.
* GET /events    -> Server-Sent Events stream; emits 'data: reload\\n\\n'
                    every time a rebuild finishes successfully.
* GET /status    -> JSON status of the last build (success, elapsed,
                    timestamp). Used by the page to display compile
                    state ("building...", "✓ built in 0.4s").

Background thread polls the watched source files at POLL_INTERVAL_MS
intervals and runs `bazel build` on every detected change, the same
way `latex_serve` does. On success it bumps a counter and pings every
connected SSE listener.

No third-party Python deps. PDF.js is pulled from
cdn.jsdelivr.net at page-load time — the rule deliberately doesn't
vendor a ~3 MB JS bundle. Users without internet at preview-time can
fall back to `latex_serve` (system viewer).
"""

from __future__ import annotations

import gzip
import json
import os
import queue
import re
import shutil
import signal
import subprocess
import sys
import threading
import time
import webbrowser
from dataclasses import dataclass, field
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import quote

# Filled in by `latex_serve_web`:
DOCUMENT_LABEL = "{{DOCUMENT_LABEL}}"
PDF_RELPATH = "{{PDF_RELPATH}}"
SYNCTEX_RELPATH = "{{SYNCTEX_RELPATH}}"
WATCHED_PATHS_RAW = """\
{{WATCHED_PATHS}}"""
POLL_INTERVAL_MS = int("{{POLL_INTERVAL}}")
DEBOUNCE_MS = int("{{DEBOUNCE_MS}}")
DEBOUNCE_MAX_MS = int("{{DEBOUNCE_MAX_MS}}")
PORT = int("{{PORT}}")
DOCUMENT_NAME = "{{DOCUMENT_NAME}}"
OPEN_ON_START = bool(int("{{OPEN_ON_START}}"))

# Paths to the vendored PDF.js files within the launcher's runfiles
# tree. The server reads them once on startup and serves the bytes at
# /_pdfjs/pdf.mjs and /_pdfjs/pdf.worker.mjs.
PDFJS_LIB_RUNFILE = "{{PDFJS_LIB_RUNFILE}}"
PDFJS_WORKER_RUNFILE = "{{PDFJS_WORKER_RUNFILE}}"

# Path (within runfiles) to the pure-Python PDF chunker. Loaded
# lazily on first successful build to compute the content-addressed
# manifest for incremental PDF transfer. See tools/pdf_chunks.py
# for the parser, and the do_GET branches for /pdf-manifest and
# /chunk/<hash> below for the wire shape consumed by the browser.
PDF_CHUNKS_RUNFILE = "{{PDF_CHUNKS_RUNFILE}}"

# Serve-time cache management. Non-empty only when the document
# takes the implicit-pipeline path; see latex/private/latex_serve_web.bzl
# and tools/serve_cache.py for the full design.
ENABLE_SERVE_CACHE = bool("{{ENABLE_SERVE_CACHE}}")
SERVE_CACHE_RUNFILE = "{{SERVE_CACHE_RUNFILE}}"
PRIME_MAIN_RUNFILE = "{{PRIME_MAIN_RUNFILE}}"
PRIME_TECTONIC_RUNFILE = "{{PRIME_TECTONIC_RUNFILE}}"
PRIME_POPULATE_TOOL_RUNFILE = "{{PRIME_POPULATE_TOOL_RUNFILE}}"
PRIME_STAGING_LIB_RUNFILE = "{{PRIME_STAGING_LIB_RUNFILE}}"
PRIME_BIBER_RUNFILE = "{{PRIME_BIBER_RUNFILE}}"
PRIME_USE_SYSTEM_BIBER = bool("{{PRIME_USE_SYSTEM_BIBER}}")
PRIME_SRCS_RAW = """\
{{PRIME_SRCS}}"""
PRIME_PKG_FILES_RAW = """\
{{PRIME_PKG_FILES}}"""

# Browser-side URLs for the same files. Centralised so the HTML
# template is just a format string.
PDFJS_LIB = "/_pdfjs/pdf.mjs"
PDFJS_WORKER = "/_pdfjs/pdf.worker.mjs"

# True iff this serve target was built against a latex_document with
# synctex = True. Used to gate the reverse-sync endpoint and the
# corresponding UI affordance in the browser.
SYNCTEX_ENABLED = bool(SYNCTEX_RELPATH)


# -----------------------------------------------------------------------------
# SyncTeX
# -----------------------------------------------------------------------------
#
# SyncTeX is the (de facto) standard for mapping between PDF coordinates
# and source-file (file, line) tuples. Tectonic emits a `<stem>.synctex.gz`
# alongside the PDF when `latex_document(synctex = True)`. The format is
# documented at https://github.com/jlaurens/synctex.
#
# We need only reverse-sync here (PDF click → source location). The
# parser is intentionally minimal: it reads the Input: directory and the
# bracketed box records, ignoring glyph-level annotations that aren't
# useful for click-level resolution. Forward-sync (source → PDF) is
# similar but inverted; we leave it as a future addition.


# SyncTeX uses "scaled points": 1 sp = 1/65536 pt = 1/(65536*72) inch.
# PDF.js reports coordinates in PDF points (1 pt). The exact factor
# between the two depends on the engine's TeX resolution but 65536 is
# the canonical conversion used everywhere.
SYNCTEX_SP_PER_PT = 65536


@dataclass(frozen=True)
class SyncTeXBox:
    """One box record from the SyncTeX content section.

    All coordinates are in scaled points. (x, y) is the box origin
    (bottom-left in TeX's coordinate system). w, h, d are width,
    height-above-baseline, and depth-below-baseline.
    """
    page: int
    file_id: int
    line: int
    x: int
    y: int
    w: int
    h: int
    d: int

    def contains(self, page: int, sp_x: int, sp_y: int) -> bool:
        if self.page != page:
            return False
        if not (self.x <= sp_x <= self.x + self.w):
            return False
        # In SyncTeX's coordinate system y grows downward and the box
        # extends from (y - h) to (y + d) — total height = h + d.
        return (self.y - self.h) <= sp_y <= (self.y + self.d)

    def area(self) -> int:
        return self.w * (self.h + self.d)


# Records of the form:
#   [page,line:x,y:w,h,d
#   (page,line:x,y:w,h,d
# Tectonic also emits 'h', 'v', 'g', 'k', 'x', '$' records for glyph
# runs; we ignore those for click-level resolution.
_BOX_RE = re.compile(
    r"^[\[(](?P<file>\d+),(?P<line>\d+):"
    r"(?P<x>-?\d+),(?P<y>-?\d+):"
    r"(?P<w>-?\d+),(?P<h>-?\d+),(?P<d>-?\d+)",
)


class SyncTeXIndex:
    """Parsed SyncTeX file, queryable by (page, x, y) in PDF points."""

    def __init__(self, inputs: dict[int, Path], boxes: list[SyncTeXBox]) -> None:
        self._inputs = inputs
        self._boxes = boxes

    @classmethod
    def from_file(cls, path: Path) -> "SyncTeXIndex":
        if path.suffix == ".gz":
            with gzip.open(path, "rt", encoding="utf-8", errors="replace") as fp:
                lines = fp.readlines()
        else:
            with path.open("r", encoding="utf-8", errors="replace") as fp:
                lines = fp.readlines()

        inputs: dict[int, Path] = {}
        boxes: list[SyncTeXBox] = []
        current_page = 0
        in_content = False

        for raw in lines:
            line = raw.rstrip("\n")
            if not in_content:
                if line.startswith("Input:"):
                    # Input:<id>:<path>
                    parts = line.split(":", 2)
                    if len(parts) == 3 and parts[2]:
                        try:
                            fid = int(parts[1])
                        except ValueError:
                            continue
                        inputs[fid] = Path(parts[2])
                elif line == "Content:":
                    in_content = True
                continue

            # In the Content section. Page boundaries:
            #   {N  starts page N
            #   }N  ends page N
            if line.startswith("{"):
                try:
                    current_page = int(line[1:].split(",")[0])
                except ValueError:
                    pass
                continue
            if line.startswith("}"):
                current_page = 0
                continue
            if line.startswith("!"):
                # `!N` is a hint that the next box's offset can be
                # derived; we don't care about that level of detail.
                continue

            m = _BOX_RE.match(line)
            if not m:
                continue
            try:
                box = SyncTeXBox(
                    page=current_page,
                    file_id=int(m.group("file")),
                    line=int(m.group("line")),
                    x=int(m.group("x")),
                    y=int(m.group("y")),
                    w=int(m.group("w")),
                    h=int(m.group("h")),
                    d=int(m.group("d")),
                )
            except ValueError:
                continue
            if box.w <= 0 or (box.h + box.d) <= 0:
                continue
            boxes.append(box)

        return cls(inputs=inputs, boxes=boxes)

    def reverse_lookup(
        self,
        page: int,
        x_pt: float,
        y_pt: float,
    ) -> tuple[Path, int] | None:
        """Map a PDF-point click to a (source_path, line) tuple.

        Returns None if no box on the given page contains the point.
        """
        sp_x = int(x_pt * SYNCTEX_SP_PER_PT)
        sp_y = int(y_pt * SYNCTEX_SP_PER_PT)

        best: SyncTeXBox | None = None
        for box in self._boxes:
            if not box.contains(page, sp_x, sp_y):
                continue
            if best is None or box.area() < best.area():
                best = box
        if best is None:
            return None
        path = self._inputs.get(best.file_id)
        if path is None:
            return None
        return (path, best.line)


# -----------------------------------------------------------------------------
# Build state
# -----------------------------------------------------------------------------


class BuildState:
    """Thread-safe shared state between the watcher and HTTP handlers.

    The HTTP server hands out an SSE listener queue per connected
    client, plus a `current` snapshot for /status responses. The
    watcher pushes a `tick` to every queue on every successful build;
    handlers translate that into an SSE message.

    Holds three caches that get invalidated on every successful
    build:

    * ``_synctex`` — parsed SyncTeX index for click-to-source.
    * ``_pdf_manifest`` — content-addressed PDF chunk manifest
      (for incremental PDF transfer; see ``Manifest`` in
      ``tools/pdf_chunks.py``).
    * The on-disk chunks directory; managed externally by the
      watcher post-build hook.
    """

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._listeners: list[queue.Queue[str]] = []
        self._build_count: int = 0
        self._last_success: bool = False
        self._last_elapsed: float = 0.0
        self._last_finished_at: float = 0.0
        self._last_message: str = "starting up..."
        # Lazily-parsed SyncTeX index for the current build. We
        # invalidate this on every successful build and re-parse on
        # demand the next time a /sync/reverse request comes in.
        self._synctex: SyncTeXIndex | None = None
        self._synctex_mtime: float = 0.0
        # Content-addressed manifest for the current PDF. None
        # before the first successful build, or when the chunker
        # couldn't parse the PDF (cross-reference-stream-stream
        # variants we don't support, malformed PDFs, etc.). The
        # browser falls back to whole-PDF transport when this is
        # None.
        self._pdf_manifest: object | None = None  # tools.pdf_chunks.Manifest | None

    def add_listener(self) -> "queue.Queue[str]":
        q: queue.Queue[str] = queue.Queue(maxsize=8)
        with self._lock:
            self._listeners.append(q)
        return q

    def drop_listener(self, q: "queue.Queue[str]") -> None:
        with self._lock:
            if q in self._listeners:
                self._listeners.remove(q)

    def record_build(self, success: bool, elapsed: float, message: str) -> None:
        with self._lock:
            self._build_count += 1
            self._last_success = success
            self._last_elapsed = elapsed
            self._last_finished_at = time.time()
            self._last_message = message
            # Invalidate the cached SyncTeX index — the .synctex.gz
            # file on disk has just changed.
            self._synctex = None
            self._synctex_mtime = 0.0
            # We do NOT invalidate _pdf_manifest here. The watcher
            # thread updates it explicitly via update_manifest()
            # after computing the chunk manifest off the new PDF.
            # Until that runs, the previous manifest is still
            # technically valid: chunks are content-addressed, so a
            # client requesting a hash from the old manifest gets
            # the same bytes it would get from the new one (if the
            # hash also appears in the new manifest) or a 404 (if
            # not). The browser handles both cases.
            listeners = list(self._listeners)
        # Notify outside the lock so a slow listener can't block the
        # build thread for more than the per-queue timeout.
        event = "reload" if success else "build-failed"
        for q in listeners:
            try:
                q.put(event, timeout=0.1)
            except queue.Full:
                # Slow listener; drop it. It can reconnect.
                pass

    def update_manifest(self, manifest: object | None) -> None:
        """Install a freshly-computed manifest. Thread-safe.

        ``manifest`` is a ``tools.pdf_chunks.Manifest`` or ``None``
        (the latter signals "PDF couldn't be parsed; fall back to
        whole-PDF transport"). Called from the watcher thread
        after each successful build.
        """
        with self._lock:
            self._pdf_manifest = manifest

    def get_manifest(self) -> object | None:
        with self._lock:
            return self._pdf_manifest

    def snapshot(self) -> dict[str, object]:
        with self._lock:
            return {
                "build_count": self._build_count,
                "last_success": self._last_success,
                "last_elapsed_seconds": round(self._last_elapsed, 3),
                "last_finished_at": self._last_finished_at,
                "last_message": self._last_message,
                "synctex_enabled": SYNCTEX_ENABLED,
            }

    def get_synctex(self, path: Path) -> SyncTeXIndex | None:
        """Return a parsed SyncTeXIndex, re-parsing if the file has changed.

        Thread-safe. Returns None if the file doesn't exist (e.g. the
        build failed before producing a .synctex.gz).
        """
        try:
            mtime = path.stat().st_mtime
        except FileNotFoundError:
            return None
        with self._lock:
            if self._synctex is not None and self._synctex_mtime == mtime:
                return self._synctex
        # Parse outside the lock — parsing can take tens of ms on
        # multi-MB synctex files and we don't want to block /status or
        # /events listeners.
        parsed = SyncTeXIndex.from_file(path)
        with self._lock:
            self._synctex = parsed
            self._synctex_mtime = mtime
        return parsed


# -----------------------------------------------------------------------------
# Watcher
# -----------------------------------------------------------------------------


def snapshot_mtimes(paths: list[Path]) -> dict[Path, float]:
    """Stat every watched path; missing files contribute 0.0."""
    result: dict[Path, float] = {}
    for path in paths:
        try:
            result[path] = path.stat().st_mtime_ns
        except FileNotFoundError:
            result[path] = 0.0
    return result


def run_bazel_build(
    workspace: Path,
    cache_ctx: "ServeCacheContext | None" = None,
) -> tuple[bool, float, str]:
    """Run `bazel build <DOCUMENT_LABEL>` from the workspace root.

    Returns (success, elapsed_seconds, summary_message).

    When ``cache_ctx`` is provided (i.e. the document takes the
    implicit-pipeline path and ``latex_serve_web`` has primed a
    persistent cache snapshot), the override flag and a cache-nonce
    action-env are appended so the compile action consumes the
    snapshot instead of the implicit populate-cache pipeline.
    """
    start = time.monotonic()
    cmd = [
        "bazel",
        "build",
        "--watchfs",
        "--noshow_progress",
    ]
    if cache_ctx is not None:
        # Hand the compile action the *extracted* cache directory
        # rather than the snapshot tarball: skips ~100-500 ms of
        # gzip-decompression + 300+ file writes per warm rebuild
        # on macOS. The compile action discriminates between the
        # two by suffix (.tar.gz -> tarball, anything else ->
        # directory). See latex/private/latex_document.bzl.
        cmd.append(
            "--@rules_latex//latex:_serve_cache_override={}".format(
                cache_ctx.layout.extracted,
            ),
        )
        cmd.append(
            "--action_env=LATEX_SERVE_CACHE_NONCE={}".format(
                cache_ctx.module.cache_nonce(cache_ctx.layout),
            ),
        )
    # When synctex is enabled the .synctex.gz file lives in a non-default
    # OutputGroup. Without --output_groups=+synctex bazel won't actually
    # materialise it in bazel-bin/, even though the target is up-to-date,
    # and the reverse-sync endpoint will then 404 ("synctex file not
    # produced yet"). See latex/private/latex_document.bzl where the
    # output is exposed via OutputGroupInfo(synctex = ...).
    if SYNCTEX_ENABLED:
        cmd.append("--output_groups=+synctex")
    cmd.append(DOCUMENT_LABEL)
    try:
        result = subprocess.run(
            cmd,
            cwd=workspace,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        return (
            False,
            time.monotonic() - start,
            "ERROR: bazel not found on PATH",
        )
    elapsed = time.monotonic() - start
    if result.returncode == 0:
        return (True, elapsed, f"built in {elapsed:.2f}s")
    # Auto-recovery: if the failure looks like a missing cached
    # resource and we have a cache to re-prime, do so and retry the
    # build exactly once.
    if cache_ctx is not None and cache_ctx.module.looks_like_missing_resource(
        result.stderr.encode("utf-8", errors="replace"),
    ):
        print(
            "latex_serve_web: build failed with what looks like a "
            "missing cached resource; re-priming and retrying...",
            file=sys.stderr,
            flush=True,
        )
        try:
            cache_ctx.module.invalidate_for_reprime(cache_ctx.layout)
            cache_ctx.module.run_prime(cache_ctx.layout, cache_ctx.spec, workspace)
        except Exception as e:
            sys.stderr.write(f"latex_serve_web: re-prime failed: {e}\n")
            sys.stderr.write(result.stderr)
            sys.stderr.flush()
            return (False, elapsed, f"BUILD FAILED ({elapsed:.2f}s)")
        # Retry the build with the freshly-primed cache.
        cmd_retry = list(cmd)
        # Update the nonce because run_prime bumped the snapshot's
        # mtime, and we want the compile action's cache key to
        # change so it actually re-runs.
        for i, arg in enumerate(cmd_retry):
            if arg.startswith("--action_env=LATEX_SERVE_CACHE_NONCE="):
                cmd_retry[i] = "--action_env=LATEX_SERVE_CACHE_NONCE={}".format(
                    cache_ctx.module.cache_nonce(cache_ctx.layout),
                )
                break
        retry_start = time.monotonic()
        result = subprocess.run(
            cmd_retry,
            cwd=workspace,
            capture_output=True,
            text=True,
        )
        retry_elapsed = time.monotonic() - retry_start
        total_elapsed = time.monotonic() - start
        if result.returncode == 0:
            return (
                True,
                total_elapsed,
                f"built in {total_elapsed:.2f}s (after re-prime; "
                f"retry {retry_elapsed:.2f}s)",
            )
        sys.stderr.write(result.stderr)
        sys.stderr.flush()
        return (
            False,
            total_elapsed,
            f"BUILD FAILED after re-prime ({total_elapsed:.2f}s)",
        )
    # Surface stderr to the operator's console; the browser only sees
    # the summary string.
    sys.stderr.write(result.stderr)
    sys.stderr.flush()
    return (False, elapsed, f"BUILD FAILED ({elapsed:.2f}s)")


@dataclass
class _DebouncerState:
    """Mutable FSM state used by the watcher loop. See
    ``watcher_loop`` for the state-transition rules.

    Lives in a dataclass (rather than a tuple or naked vars) so
    the unit tests can construct it directly and step the FSM
    deterministically — separating the time-driven loop from the
    pure-function decision logic.
    """

    idle_deadline: float | None = None
    deadline_max: float | None = None
    pending_changes: list = field(default_factory=list)


def _debouncer_step(
    state: _DebouncerState,
    fresh_changes: list,
    now: float,
    debounce_window: float,
    debounce_max: float,
) -> tuple[bool, bool]:
    """Apply one watcher-loop tick to the FSM in ``state``.

    Inputs:
      * ``fresh_changes``: paths whose mtime changed since the
        last poll. Empty when the poll detected no change.
      * ``now``: the loop's notion of monotonic time (seconds).
      * ``debounce_window``: how much idle to require before firing.
      * ``debounce_max``: hard cap on the total debounce span.

    Returns ``(should_fire, hit_hard_cap)``:

      * ``should_fire`` — True iff this tick should kick off a
        build. When True the caller should drain
        ``state.pending_changes`` (it has the coalesced burst)
        and reset the FSM via ``state.idle_deadline = None``
        etc. — see ``watcher_loop`` for the canonical sequence.
      * ``hit_hard_cap`` — True iff the fire was triggered by
        the hard cap rather than the idle window expiring.
        Surfaced so the loop can log the rare case.

    Side effect: ``state`` is mutated in-place to reflect the
    new pending-change set and (re-pushed) deadlines.
    """
    if fresh_changes:
        # New burst or extension of an existing burst.
        if state.idle_deadline is None:
            state.deadline_max = now + debounce_max
        state.idle_deadline = now + debounce_window
        for p in fresh_changes:
            if p not in state.pending_changes:
                state.pending_changes.append(p)

    if state.idle_deadline is None:
        return (False, False)

    ready_idle = now >= state.idle_deadline
    ready_max = state.deadline_max is not None and now >= state.deadline_max
    if not (ready_idle or ready_max):
        return (False, False)

    return (True, ready_max and not ready_idle)


def watcher_loop(
    workspace: Path,
    state: BuildState,
    cache_ctx: "ServeCacheContext | None" = None,
    pdf_chunks_ctx: "PdfChunksContext | None" = None,
) -> None:
    """Background thread: detect source changes, debounce them, run
    `bazel build`.

    The watcher is a small state machine:

    * IDLE — no pending changes. Polls the watched paths every
      ``POLL_INTERVAL_MS``. On a detected change → DEBOUNCING.
    * DEBOUNCING — at least one change has been seen since the
      last build. Keeps polling; each fresh change pushes the
      idle deadline out by ``DEBOUNCE_MS``. A hard cap
      (``deadline_max``, set on entry to this state from
      ``debounce_max_ms``) fires the build regardless of fresh
      activity to bound worst-case wait time. When ``now >=
      idle_deadline`` *or* ``now >= deadline_max``, transitions
      to BUILDING and kicks off a build.
    * BUILDING — a build is in flight (synchronous in this
      thread). When the build completes the loop returns to the
      top; any change detected during the build will look fresh
      on the next poll and trigger a new DEBOUNCING window.

    The decision logic is factored into ``_debouncer_step`` so it
    can be unit-tested without driving the real wall-clock or
    spawning ``bazel build``.

    Why debouncing helps:

    * Editors that write-then-rename (vim, neovim) produce two
      mtime bumps for one logical save; without debouncing we'd
      fire two builds.
    * Editors with format-on-save (Prettier-like tooling for
      LaTeX, or running ``texfmt`` in a hook) write the file
      twice: format-edit, then user-save. Same problem.
    * A user typing through a long word touches the buffer many
      times if the editor auto-saves; we want one build at the
      end of the word, not one per character.

    With ``DEBOUNCE_MS = 0`` this collapses to the pre-v0.3.3
    fire-on-every-poll behaviour (the FSM still runs but every
    tick that sees a change immediately satisfies ``now >=
    idle_deadline``).
    """
    watched_paths = [
        workspace / rel
        for rel in WATCHED_PATHS_RAW.splitlines()
        if rel.strip()
    ]
    poll_interval = POLL_INTERVAL_MS / 1000.0
    debounce_window = DEBOUNCE_MS / 1000.0
    debounce_max = DEBOUNCE_MAX_MS / 1000.0

    # Initial build so the first browser page-load has something to
    # display.
    success, elapsed, msg = run_bazel_build(workspace, cache_ctx)
    print(f"latex_serve_web: initial build: {msg}", flush=True)
    state.record_build(success, elapsed, msg)
    if success:
        _compute_manifest_post_build(state, workspace, pdf_chunks_ctx)

    last_mtimes = snapshot_mtimes(watched_paths)
    fsm = _DebouncerState()

    while True:
        time.sleep(poll_interval)
        now = time.monotonic()

        # Detect changes since the last poll.
        current = snapshot_mtimes(watched_paths)
        fresh_changes = [
            p for p, m in current.items()
            if m != last_mtimes.get(p, 0.0)
        ]
        last_mtimes = current

        was_idle = fsm.idle_deadline is None
        if fresh_changes and was_idle:
            ts = time.strftime("%H:%M:%S")
            print(
                f"[{ts}] changed: " +
                ", ".join(
                    str(p.relative_to(workspace))
                    for p in fresh_changes
                ),
                flush=True,
            )

        should_fire, hit_hard_cap = _debouncer_step(
            fsm,
            fresh_changes,
            now,
            debounce_window,
            debounce_max,
        )
        if not should_fire:
            continue

        # Transition: DEBOUNCING -> BUILDING. Snapshot the coalesced
        # changes and clear the FSM *before* the build so changes
        # that land during the build start a fresh debounce window
        # naturally on the next iteration. We do NOT re-snapshot
        # mtimes here: the last_mtimes captured at the top of this
        # iteration is what we want preserved across the build, so
        # post-build polls see in-flight saves as fresh changes.
        coalesced = list(fsm.pending_changes)
        fsm.idle_deadline = None
        fsm.deadline_max = None
        fsm.pending_changes.clear()

        if hit_hard_cap:
            print(
                "  (debounce hard cap reached; firing build)",
                flush=True,
            )
        if len(coalesced) > 1:
            print(
                "  (coalesced " + str(len(coalesced)) + " changes: " +
                ", ".join(
                    str(p.relative_to(workspace)) for p in coalesced
                ) + ")",
                flush=True,
            )

        success, elapsed, msg = run_bazel_build(workspace, cache_ctx)
        print(f"  {msg}", flush=True)
        state.record_build(success, elapsed, msg)
        if success:
            _compute_manifest_post_build(state, workspace, pdf_chunks_ctx)


# -----------------------------------------------------------------------------
# HTTP handlers
# -----------------------------------------------------------------------------


INDEX_HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{document_name} – live preview</title>
<style>
  * {{ box-sizing: border-box; }}
  body {{
    font: 13px/1.4 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    margin: 0; background: #2b2b2b; color: #e8e8e8;
    display: grid; grid-template-rows: auto 1fr auto;
    height: 100vh;
  }}
  header {{
    display: flex; gap: 12px; align-items: center;
    padding: 8px 12px; background: #1d1d1d;
    border-bottom: 1px solid #000;
  }}
  header h1 {{
    margin: 0; font-size: 13px; font-weight: 600;
    letter-spacing: 0.02em;
  }}
  #status {{
    margin-left: auto; padding: 3px 9px; border-radius: 4px;
    font-variant-numeric: tabular-nums;
    transition: background 0.2s;
  }}
  #status.ok      {{ background: #1e3a1e; color: #b4f0b4; }}
  #status.fail    {{ background: #4a1818; color: #ffb4b4; }}
  #status.building {{ background: #3a3a1e; color: #f0f0b4; }}
  #status.idle    {{ background: #333; color: #aaa; }}
  #zoom-controls {{ display: flex; gap: 6px; }}
  #zoom-controls button {{
    background: #333; color: #e8e8e8; border: 1px solid #555;
    padding: 3px 9px; border-radius: 4px; font: inherit; cursor: pointer;
  }}
  #zoom-controls button:hover {{ background: #444; }}
  #viewer {{
    overflow: auto; padding: 16px; background: #2b2b2b;
    text-align: center;
  }}
  #viewer canvas {{
    display: block; margin: 0 auto 12px; background: white;
    box-shadow: 0 2px 8px rgba(0,0,0,0.4);
    cursor: var(--canvas-cursor, default);
  }}
  body.synctex #viewer canvas {{ --canvas-cursor: crosshair; }}
  #empty {{ color: #888; padding: 32px; }}
  footer {{
    padding: 6px 12px; background: #1d1d1d;
    border-top: 1px solid #000;
    font-size: 12px; color: #888;
    min-height: 28px;
  }}
  #sync-result {{ color: #b4d8f0; font-family: ui-monospace, monospace; }}
  #sync-result a {{ color: #b4d8f0; text-decoration: underline; }}
</style>
</head>
<body class="{synctex_body_class}">
<header>
  <h1>{document_name}</h1>
  <div id="zoom-controls">
    <button id="zoom-out" title="Zoom out">−</button>
    <button id="zoom-reset" title="Reset zoom">100%</button>
    <button id="zoom-in" title="Zoom in">+</button>
  </div>
  <div id="status" class="idle">connecting…</div>
</header>
<div id="viewer"><div id="empty">waiting for first build…</div></div>
<footer>
  <span id="sync-result">{synctex_hint}</span>
</footer>

<script type="module">
import * as pdfjsLib from "{pdfjs_lib}";
pdfjsLib.GlobalWorkerOptions.workerSrc = "{pdfjs_worker}";

const SYNCTEX_ENABLED = {synctex_enabled};
const viewer = document.getElementById("viewer");
const statusEl = document.getElementById("status");
const syncResultEl = document.getElementById("sync-result");
let currentDoc = null;
let scale = 1.5;
// Map canvas DOM element -> its rendered viewport (so click handlers
// can convert client coords back to PDF coords).
const canvasViewports = new WeakMap();

// -----------------------------------------------------------------------
// Content-addressed PDF chunk cache
// -----------------------------------------------------------------------
//
// Mirrors the server-side chunk store (see tools/pdf_chunks.py):
// each PDF object is stored once under its SHA-256 hash. On every
// reload we fetch the latest manifest, which lists object byte
// ranges and hashes; chunks whose hashes the client already has
// are served from this in-memory cache, and only new hashes are
// fetched from /chunk/<hash>.
//
// The cache survives across reloads (it's module-scope) but is
// reset by a page refresh. That's fine: the user's browser will
// fetch /chunk/<hash> with `Cache-Control: public, max-age=...,
// immutable` headers, so the second fetch comes from the
// browser's HTTP cache and is nearly free.
//
// Cap the cache at a modest number of entries to bound memory
// usage. LRU eviction would be ideal but is overkill: the bound
// here is loose, and chunks evicted from this Map can still be
// re-fetched (the server keeps them on disk and the browser's
// HTTP cache reduces wire transfer to ~0).
const CHUNK_CACHE_MAX_ENTRIES = 1000;
const chunkCache = new Map();

function rememberChunk(hash, bytes) {{
  if (chunkCache.size >= CHUNK_CACHE_MAX_ENTRIES) {{
    // Evict the oldest entry (Map preserves insertion order).
    const oldestKey = chunkCache.keys().next().value;
    if (oldestKey !== undefined) chunkCache.delete(oldestKey);
  }}
  chunkCache.set(hash, bytes);
}}

async function fetchChunk(hash) {{
  const cached = chunkCache.get(hash);
  if (cached) return cached;
  const resp = await fetch(`/chunk/${{hash}}`);
  if (!resp.ok) {{
    throw new Error(`chunk ${{hash}} fetch failed: ${{resp.status}}`);
  }}
  const buf = new Uint8Array(await resp.arrayBuffer());
  rememberChunk(hash, buf);
  return buf;
}}

async function fetchPdfRange(begin, end) {{
  // Fetch [begin, end) from /pdf using HTTP Range. Used for
  // skeleton ranges (PDF header, gaps between objects, the
  // trailer) — anything not covered by a content-addressed
  // chunk.
  const resp = await fetch("/pdf", {{
    headers: {{ "Range": `bytes=${{begin}}-${{end - 1}}` }},
  }});
  if (!(resp.status === 206 || resp.status === 200)) {{
    throw new Error(`/pdf range ${{begin}}-${{end - 1}} failed: ${{resp.status}}`);
  }}
  return new Uint8Array(await resp.arrayBuffer());
}}

// Custom PDFDataRangeTransport that serves byte ranges from the
// content-addressed chunk cache where possible, falling back to
// /pdf with HTTP Range for skeleton bytes (header/xref/trailer).
class ChunkedTransport extends pdfjsLib.PDFDataRangeTransport {{
  constructor(manifest) {{
    // initialData is empty: PDF.js will request the ranges it
    // needs via requestDataRange.
    super(manifest.pdfSize, new Uint8Array(0));
    this.manifest = manifest;
    // Sort chunks by start offset for fast lookups; the server
    // emits them sorted but defending against a future change is
    // cheap.
    this.sortedRanges = [...manifest.ranges].sort(
      (a, b) => a.start - b.start
    );
    queueMicrotask(() => this.transportReady());
  }}

  async requestDataRange(begin, end) {{
    // PDF.js's API has end inclusive in some places and exclusive
    // in others; the spec the worker sends here is half-open
    // [begin, end). Clamp to pdfSize for safety.
    end = Math.min(end, this.manifest.pdfSize);
    if (begin >= end) {{
      this.onDataRange(begin, new Uint8Array(0));
      return;
    }}
    try {{
      const bytes = await this._assemble(begin, end);
      this.onDataRange(begin, bytes);
    }} catch (err) {{
      console.error("ChunkedTransport: range fetch failed", err);
      // PDF.js retries on failure. Don't call onDataRange; the
      // request just times out. Better than throwing here, which
      // would break the worker.
    }}
  }}

  async _assemble(begin, end) {{
    // Walk [begin, end), serving each sub-range from either the
    // covering chunk or a /pdf Range fetch. Concatenate into one
    // buffer for delivery.
    const segments = [];
    let cursor = begin;
    // Find the first chunk whose end > begin (binary search would
    // be overkill: 20-100 chunks per CV-sized PDF).
    let i = 0;
    while (i < this.sortedRanges.length && this.sortedRanges[i].end <= begin) {{
      i++;
    }}
    while (cursor < end) {{
      if (i < this.sortedRanges.length && this.sortedRanges[i].start < end) {{
        const r = this.sortedRanges[i];
        if (cursor < r.start) {{
          // Skeleton gap before this chunk.
          const gapEnd = Math.min(r.start, end);
          segments.push(await fetchPdfRange(cursor, gapEnd));
          cursor = gapEnd;
        }} else {{
          // Inside / overlapping the chunk. Fetch the whole
          // chunk (it's content-addressed; we'll cache it) and
          // slice out the requested sub-range.
          const chunkBytes = await fetchChunk(r.hash);
          const sliceStart = cursor - r.start;
          const sliceEnd = Math.min(end, r.end) - r.start;
          segments.push(chunkBytes.subarray(sliceStart, sliceEnd));
          cursor = r.start + sliceEnd;
          if (cursor >= r.end) i++;
        }}
      }} else {{
        // Past the last chunk's end — pure skeleton.
        segments.push(await fetchPdfRange(cursor, end));
        cursor = end;
      }}
    }}
    if (segments.length === 1) return segments[0];
    // Concatenate segments into one buffer.
    const total = segments.reduce((s, seg) => s + seg.length, 0);
    const out = new Uint8Array(total);
    let off = 0;
    for (const seg of segments) {{
      out.set(seg, off);
      off += seg.length;
    }}
    return out;
  }}
}}

// Background-prefetch every chunk in the manifest. Runs after
// PDF.js's initial getDocument promise resolves so we don't
// compete with the worker for bandwidth on the first render. By
// the time the user starts scrolling, every chunk is in
// `chunkCache` and PDF.js's per-page byte fetches are
// instant. Best-effort: failures are silent and don't affect
// rendering (PDF.js will fetch on-demand if a chunk's missing).
async function prefetchChunks(manifest) {{
  // Concurrency: keep it modest so we don't saturate localhost
  // connections and starve user-initiated fetches.
  const queue = manifest.ranges
    .filter(r => !chunkCache.has(r.hash))
    .map(r => r.hash);
  const workerCount = 4;
  async function worker() {{
    while (queue.length) {{
      const hash = queue.shift();
      try {{
        await fetchChunk(hash);
      }} catch (e) {{ /* ignore */ }}
    }}
  }}
  await Promise.all(
    Array.from({{ length: workerCount }}, () => worker())
  );
}}

function setStatus(cls, text) {{
  statusEl.className = cls;
  statusEl.textContent = text;
}}

async function fetchManifest() {{
  // Returns a manifest object, or null if the server can't
  // produce one (e.g. cross-reference-stream PDF the chunker
  // doesn't understand, or chunking is disabled). On null we
  // fall back to whole-PDF transport.
  try {{
    const resp = await fetch("/pdf-manifest");
    if (!resp.ok) return null;
    return await resp.json();
  }} catch (err) {{
    return null;
  }}
}}

async function renderDocument() {{
  setStatus("building", "rendering…");
  try {{
    const manifest = await fetchManifest();
    let pdf;
    if (manifest && manifest.ranges && manifest.ranges.length > 0) {{
      // Chunked path: serve byte ranges from the content-
      // addressed cache (with HTTP-Range fallback for
      // skeleton bytes).
      const transport = new ChunkedTransport(manifest);
      const loadingTask = pdfjsLib.getDocument({{ range: transport }});
      pdf = await loadingTask.promise;
      // Kick off prefetch in the background; don't await.
      prefetchChunks(manifest).catch(() => {{}});
    }} else {{
      // Fallback: pull the whole PDF in one request. Used for
      // documents the chunker couldn't parse, and for first-load
      // before any manifest exists. Cache-busts via the query
      // string so the browser fetches fresh bytes.
      const bust = Date.now();
      const loadingTask = pdfjsLib.getDocument(`/pdf?t=${{bust}}`);
      pdf = await loadingTask.promise;
    }}
    currentDoc = pdf;
    await renderAllPages(pdf);
  }} catch (err) {{
    setStatus("fail", `render error: ${{err.message || err}}`);
    console.error(err);
  }}
}}

async function renderAllPages(pdf) {{
  const prevScroll = {{ top: viewer.scrollTop, left: viewer.scrollLeft }};
  const fresh = document.createElement("div");
  const dpr = window.devicePixelRatio || 1;
  for (let i = 1; i <= pdf.numPages; i++) {{
    const page = await pdf.getPage(i);
    const viewport = page.getViewport({{ scale }});
    const canvas = document.createElement("canvas");
    // Render at devicePixelRatio for crisp output on HiDPI displays;
    // CSS pins the displayed size to the un-scaled viewport dimensions.
    canvas.width = Math.floor(viewport.width * dpr);
    canvas.height = Math.floor(viewport.height * dpr);
    canvas.style.width = `${{viewport.width}}px`;
    canvas.style.height = `${{viewport.height}}px`;
    canvas.dataset.pageNumber = String(i);
    const ctx = canvas.getContext("2d");
    const transform = dpr !== 1 ? [dpr, 0, 0, dpr, 0, 0] : null;
    await page.render({{ canvasContext: ctx, viewport, transform }}).promise;
    canvasViewports.set(canvas, viewport);
    if (SYNCTEX_ENABLED) {{
      canvas.addEventListener("click", onCanvasClick);
    }}
    fresh.appendChild(canvas);
  }}
  viewer.replaceChildren(fresh);
  viewer.scrollTo(prevScroll);
  await refreshStatus();
}}

async function refreshStatus() {{
  try {{
    const r = await fetch("/status");
    const s = await r.json();
    if (s.last_success) {{
      setStatus("ok", `✓ ${{s.last_message}} · build #${{s.build_count}}`);
    }} else {{
      setStatus("fail", `${{s.last_message}}`);
    }}
  }} catch (e) {{
    setStatus("fail", "server unreachable");
  }}
}}

async function onCanvasClick(event) {{
  const canvas = event.currentTarget;
  const viewport = canvasViewports.get(canvas);
  if (!viewport) return;
  // Convert client coordinates (page-relative pixels) to canvas
  // coordinates (account for canvas dimensions vs. displayed size).
  const rect = canvas.getBoundingClientRect();
  const cssX = event.clientX - rect.left;
  const cssY = event.clientY - rect.top;
  const cx = cssX * (canvas.width / rect.width);
  const cy = cssY * (canvas.height / rect.height);
  // PDF.js' viewport.convertToPdfPoint() maps canvas pixels back to
  // PDF points relative to the page's bottom-left.
  const [pdfX, pdfY] = viewport.convertToPdfPoint(cx, cy);
  const pageNumber = parseInt(canvas.dataset.pageNumber, 10);

  syncResultEl.textContent = "looking up source location…";
  try {{
    const r = await fetch("/sync/reverse", {{
      method: "POST",
      headers: {{ "Content-Type": "application/json" }},
      body: JSON.stringify({{ page: pageNumber, x: pdfX, y: pdfY }}),
    }});
    const body = await r.json();
    if (body.ok) {{
      syncResultEl.innerHTML =
        `→ <strong>${{escapeHtml(body.file)}}</strong>:` +
        `<strong>${{body.line}}</strong> ` +
        `(page ${{pageNumber}}, ${{pdfX.toFixed(1)}}, ${{pdfY.toFixed(1)}})`;
    }} else {{
      syncResultEl.textContent = `synctex: ${{body.error || "no match"}}`;
    }}
  }} catch (err) {{
    syncResultEl.textContent = `synctex request failed: ${{err.message || err}}`;
  }}
}}

function escapeHtml(s) {{
  return String(s).replace(/[&<>"']/g,
    c => ({{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}}[c]));
}}

const evtSrc = new EventSource("/events");
evtSrc.onmessage = (e) => {{
  if (e.data === "reload") {{
    renderDocument();
  }} else if (e.data === "build-failed" || e.data === "hello") {{
    refreshStatus();
  }}
}};
evtSrc.onerror = () => {{
  setStatus("fail", "lost connection to server");
}};

document.getElementById("zoom-in").addEventListener("click", () => {{
  scale = Math.min(scale * 1.2, 4.0);
  if (currentDoc) renderAllPages(currentDoc);
}});
document.getElementById("zoom-out").addEventListener("click", () => {{
  scale = Math.max(scale / 1.2, 0.4);
  if (currentDoc) renderAllPages(currentDoc);
}});
document.getElementById("zoom-reset").addEventListener("click", () => {{
  scale = 1.5;
  if (currentDoc) renderAllPages(currentDoc);
}});

renderDocument();
refreshStatus();
</script>
</body>
</html>
"""


class Handler(BaseHTTPRequestHandler):
    # Class-level attributes set by run_server() before this is used.
    state: BuildState
    workspace: Path
    pdfjs_lib_bytes: bytes
    pdfjs_worker_bytes: bytes
    pdf_chunks_ctx: "PdfChunksContext | None" = None

    def log_message(self, format: str, *args: object) -> None:  # noqa: A002
        # http.server is chatty by default; we already log builds
        # ourselves from the watcher thread. Suppress per-request lines.
        return

    def _send(
        self,
        status: int,
        body: bytes,
        content_type: str,
        extra_headers: dict[str, str] | None = None,
    ) -> None:
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        for k, v in (extra_headers or {}).items():
            self.send_header(k, v)
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self) -> None:  # noqa: N802 (http.server API)
        path = self.path.split("?", 1)[0]
        if path == "/":
            html = INDEX_HTML_TEMPLATE.format(
                document_name=DOCUMENT_NAME,
                pdfjs_lib=PDFJS_LIB,
                pdfjs_worker=PDFJS_WORKER,
                synctex_enabled="true" if SYNCTEX_ENABLED else "false",
                synctex_body_class="synctex" if SYNCTEX_ENABLED else "",
                synctex_hint=(
                    "click anywhere in the PDF to jump to source"
                    if SYNCTEX_ENABLED
                    else (
                        "synctex disabled (build with "
                        "latex_document(synctex = True) to enable)"
                    )
                ),
            )
            self._send(HTTPStatus.OK, html.encode("utf-8"), "text/html; charset=utf-8")
            return
        if path == "/pdf":
            self._serve_pdf_with_range()
            return
        if path == "/pdf-manifest":
            self._serve_pdf_manifest()
            return
        if path.startswith("/chunk/"):
            self._serve_chunk(path[len("/chunk/"):])
            return
        if path == "/_pdfjs/pdf.mjs":
            # ESM Javascript MIME type per the WHATWG fetch spec.
            self._send(
                HTTPStatus.OK,
                self.pdfjs_lib_bytes,
                "text/javascript; charset=utf-8",
            )
            return
        if path == "/_pdfjs/pdf.worker.mjs":
            self._send(
                HTTPStatus.OK,
                self.pdfjs_worker_bytes,
                "text/javascript; charset=utf-8",
            )
            return
        if path == "/status":
            body = json.dumps(self.state.snapshot()).encode("utf-8")
            self._send(HTTPStatus.OK, body, "application/json")
            return
        if path == "/events":
            self._stream_events()
            return
        self._send(
            HTTPStatus.NOT_FOUND,
            b"not found",
            "text/plain; charset=utf-8",
        )

    def do_POST(self) -> None:  # noqa: N802 (http.server API)
        path = self.path.split("?", 1)[0]
        if path == "/sync/reverse":
            self._handle_sync_reverse()
            return
        self._send(
            HTTPStatus.NOT_FOUND,
            b"not found",
            "text/plain; charset=utf-8",
        )

    # -------------------------------------------------------------
    # PDF transport (chunked + Range-aware /pdf)
    # -------------------------------------------------------------

    def _serve_pdf_with_range(self) -> None:
        """Serve ``/pdf`` with HTTP Range support.

        The chunked transport path on the client side relies on
        being able to fetch arbitrary byte ranges from ``/pdf``
        for the parts of the PDF that aren't covered by any
        chunk (the header, gaps between objects, the trailer).
        Without Range support, every skeleton-range fetch would
        pull the entire PDF.
        """
        pdf_path = self.workspace / "bazel-bin" / PDF_RELPATH
        try:
            file_size = pdf_path.stat().st_size
        except FileNotFoundError:
            self._send(
                HTTPStatus.NOT_FOUND,
                b"PDF not built yet.",
                "text/plain; charset=utf-8",
            )
            return

        range_header = self.headers.get("Range", "").strip()
        if not range_header:
            # No Range header: serve the whole PDF as before.
            try:
                body = pdf_path.read_bytes()
            except OSError:
                self._send(
                    HTTPStatus.INTERNAL_SERVER_ERROR,
                    b"PDF read error",
                    "text/plain; charset=utf-8",
                )
                return
            self._send(HTTPStatus.OK, body, "application/pdf")
            return

        # Parse a single byte-range "bytes=start-end". We don't
        # support multipart ranges — PDF.js doesn't request them.
        m = re.match(
            r"^bytes=(\d+)-(\d*)$",
            range_header,
        )
        if not m:
            self.send_response(HTTPStatus.REQUESTED_RANGE_NOT_SATISFIABLE)
            self.send_header("Content-Range", f"bytes */{file_size}")
            self.end_headers()
            return
        start = int(m.group(1))
        end_str = m.group(2)
        end = int(end_str) if end_str else (file_size - 1)
        if start >= file_size or end < start:
            self.send_response(HTTPStatus.REQUESTED_RANGE_NOT_SATISFIABLE)
            self.send_header("Content-Range", f"bytes */{file_size}")
            self.end_headers()
            return
        end = min(end, file_size - 1)
        length = end - start + 1
        try:
            with open(pdf_path, "rb") as fp:
                fp.seek(start)
                body = fp.read(length)
        except OSError:
            self._send(
                HTTPStatus.INTERNAL_SERVER_ERROR,
                b"PDF read error",
                "text/plain; charset=utf-8",
            )
            return
        self.send_response(HTTPStatus.PARTIAL_CONTENT)
        self.send_header("Content-Type", "application/pdf")
        self.send_header("Content-Length", str(len(body)))
        self.send_header(
            "Content-Range",
            f"bytes {start}-{end}/{file_size}",
        )
        self.send_header("Accept-Ranges", "bytes")
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)

    def _serve_pdf_manifest(self) -> None:
        """Return the JSON content-addressed manifest for the
        current PDF, or 404 when no manifest is available (the
        client then falls back to whole-PDF transport).
        """
        manifest = self.state.get_manifest()
        if manifest is None:
            self._send(
                HTTPStatus.NOT_FOUND,
                b"no manifest available",
                "text/plain; charset=utf-8",
            )
            return
        payload = {
            "pdfSize": manifest.pdf_size,
            "ranges": [
                {
                    "objectId": c.object_id,
                    "start": c.start,
                    "end": c.end,
                    "hash": c.hash,
                }
                for c in manifest.chunks
            ],
            "skeletonRanges": [
                [s, e] for s, e in manifest.skeleton_ranges
            ],
        }
        body = json.dumps(payload, separators=(",", ":")).encode("utf-8")
        self._send(HTTPStatus.OK, body, "application/json")

    def _serve_chunk(self, hash_hex: str) -> None:
        """Serve one content-addressed PDF chunk by SHA-256 hash.

        Chunks are written by the watcher's post-build hook into
        ``pdf_chunks_ctx.chunks_dir`` and served from there. We
        validate the hash format strictly to avoid path
        traversal: only 64 lowercase hex characters allowed.
        """
        if self.pdf_chunks_ctx is None:
            self._send(
                HTTPStatus.NOT_FOUND,
                b"chunking disabled on this server",
                "text/plain; charset=utf-8",
            )
            return
        if len(hash_hex) != 64 or not all(
            c in "0123456789abcdef" for c in hash_hex
        ):
            self._send(
                HTTPStatus.BAD_REQUEST,
                b"invalid chunk hash",
                "text/plain; charset=utf-8",
            )
            return
        chunk_path = self.pdf_chunks_ctx.chunks_dir / hash_hex
        try:
            body = chunk_path.read_bytes()
        except FileNotFoundError:
            self._send(
                HTTPStatus.NOT_FOUND,
                b"chunk not found",
                "text/plain; charset=utf-8",
            )
            return
        except OSError:
            self._send(
                HTTPStatus.INTERNAL_SERVER_ERROR,
                b"chunk read error",
                "text/plain; charset=utf-8",
            )
            return
        # Chunks are content-addressed by hash so they're
        # immutable: cache them aggressively in the browser. We
        # bypass _send here because it always emits
        # ``Cache-Control: no-store``, which is the wrong header
        # for immutable resources.
        self.send_response(HTTPStatus.OK)
        self.send_header("Content-Type", "application/octet-stream")
        self.send_header("Content-Length", str(len(body)))
        self.send_header(
            "Cache-Control",
            "public, max-age=31536000, immutable",
        )
        self.end_headers()
        self.wfile.write(body)

    def _handle_sync_reverse(self) -> None:
        """POST /sync/reverse — map a PDF click to a source location.

        Request body (JSON):
            {"page": 1, "x": 123.4, "y": 456.7}
            where x/y are in PDF points relative to the page's bottom-
            left corner.

        Response body (JSON):
            {"ok": true, "file": "cv.tex", "line": 42}
        or
            {"ok": false, "error": "synctex not enabled"}
        """
        if not SYNCTEX_ENABLED:
            self._send_json(
                HTTPStatus.NOT_FOUND,
                {"ok": False, "error": "synctex not enabled for this document"},
            )
            return
        try:
            length = int(self.headers.get("Content-Length", "0"))
            body_raw = self.rfile.read(length) if length else b""
            payload = json.loads(body_raw.decode("utf-8"))
            page = int(payload["page"])
            x = float(payload["x"])
            y = float(payload["y"])
        except (KeyError, ValueError, json.JSONDecodeError) as exc:
            self._send_json(
                HTTPStatus.BAD_REQUEST,
                {"ok": False, "error": "bad request: {}".format(exc)},
            )
            return

        synctex_path = self.workspace / "bazel-bin" / SYNCTEX_RELPATH
        idx = self.state.get_synctex(synctex_path)
        if idx is None:
            self._send_json(
                HTTPStatus.NOT_FOUND,
                {"ok": False, "error": "synctex file not produced yet"},
            )
            return

        result = idx.reverse_lookup(page, x, y)
        if result is None:
            self._send_json(
                HTTPStatus.OK,
                {"ok": False, "error": "no source location found"},
            )
            return
        synctex_path, line = result

        # SyncTeX records the path as tectonic saw it inside the Bazel
        # action sandbox, which is something like
        # `/private/.../execroot/_main/preamble.tex`. Map that back to
        # a workspace-relative path by matching basenames against the
        # watched source list — that's a much more useful reference
        # for an editor jump.
        resolved = self._resolve_to_workspace(synctex_path)
        self._send_json(
            HTTPStatus.OK,
            {"ok": True, "file": resolved, "line": line},
        )

    def _resolve_to_workspace(self, synctex_path: Path) -> str:
        """Map a sandbox-absolute path back to a workspace-relative one.

        Best-effort. Falls back to the original path's basename if no
        watched source matches.
        """
        basename = synctex_path.name
        for rel in WATCHED_PATHS_RAW.splitlines():
            rel = rel.strip()
            if not rel:
                continue
            if Path(rel).name == basename:
                # Confirm the workspace actually has the file at this
                # relative path. If two watched sources share a
                # basename (unusual but possible) we pick the first.
                if (self.workspace / rel).is_file():
                    return rel
        # No match in the watched sources; return the basename as a
        # last resort so editor jumps at least show a meaningful name.
        return basename

    def _send_json(self, status: int, payload: object) -> None:
        body = json.dumps(payload).encode("utf-8")
        self._send(status, body, "application/json")

    def _stream_events(self) -> None:
        self.send_response(HTTPStatus.OK)
        self.send_header("Content-Type", "text/event-stream")
        self.send_header("Cache-Control", "no-store")
        self.send_header("Connection", "keep-alive")
        # Allow same-origin only; we only ever bind to localhost so
        # this is mostly belt-and-braces.
        self.send_header("X-Accel-Buffering", "no")
        self.end_headers()

        q = self.state.add_listener()
        try:
            # Send a hello so the page knows the connection is live.
            self.wfile.write(b"data: hello\n\n")
            self.wfile.flush()

            # 15s keepalive so proxies (and python http.server's own
            # connection-handling) don't close the stream during quiet
            # periods.
            keepalive_interval = 15.0
            last_send = time.monotonic()
            while True:
                try:
                    event = q.get(timeout=1.0)
                    self.wfile.write(f"data: {event}\n\n".encode("utf-8"))
                    self.wfile.flush()
                    last_send = time.monotonic()
                except queue.Empty:
                    if time.monotonic() - last_send > keepalive_interval:
                        self.wfile.write(b": keepalive\n\n")
                        self.wfile.flush()
                        last_send = time.monotonic()
        except (BrokenPipeError, ConnectionResetError):
            pass
        finally:
            self.state.drop_listener(q)


# -----------------------------------------------------------------------------
# Editor detection
# -----------------------------------------------------------------------------
#
# When `bazel run //:doc_web` is invoked from inside a VS Code-family
# editor's integrated terminal, we can print a special URL that opens
# the preview as a tab in the same window (via the editor's built-in
# Simple Browser). The URL scheme `<editor>://vscode.simpleBrowser/show`
# is handled by Simple Browser's URI activation, which is shipped as a
# built-in extension in VS Code and inherited by its forks.
#
# Detection is best-effort: we read TERM_PROGRAM (set by VS Code,
# Cursor, and VSCodium in their integrated terminals) and bail out
# silently if there's no match. The plain http:// URL is always printed
# last so users have an unconditional fallback.


@dataclass(frozen=True)
class Editor:
    """A VS Code-family editor we can hand a Simple Browser URL to.

    `name` is human-readable (used in the printed hint). `scheme` is
    the URI scheme registered by the editor for OS-level handoff; the
    full URI is `<scheme>://vscode.simpleBrowser/show?url=<encoded>`.
    `cli` is the command-line binary used by `open_on_start` to push
    the URI into the running editor instance.
    """

    name: str
    scheme: str
    cli: str


# Map TERM_PROGRAM values (lowercased) to editors. VS Code and its
# common forks all set this on terminal startup. JetBrains IDEs set
# TERMINAL_EMULATOR=JetBrains-JediTerm but have no Simple Browser
# equivalent, so we don't list them here — users in JetBrains just see
# the plain http URL like any other terminal.
_EDITORS_BY_TERM_PROGRAM = {
    "vscode": Editor(name="VS Code", scheme="vscode", cli="code"),
    "cursor": Editor(name="Cursor", scheme="cursor", cli="cursor"),
    "vscodium": Editor(name="VSCodium", scheme="vscodium", cli="codium"),
}


def detect_editor() -> Editor | None:
    """Return the editor whose terminal we're running inside, or None.

    Reads TERM_PROGRAM and matches case-insensitively. Returns None on
    any mismatch so the caller can fall back to plain http output.
    """
    term_program = os.environ.get("TERM_PROGRAM", "").strip().lower()
    if not term_program:
        return None
    return _EDITORS_BY_TERM_PROGRAM.get(term_program)


def editor_preview_uri(editor: Editor, http_url: str) -> str:
    """Build a Simple Browser URI for `editor` wrapping `http_url`."""
    return "{}://vscode.simpleBrowser/show?url={}".format(
        editor.scheme,
        quote(http_url, safe=""),
    )


def open_in_editor(editor: Editor, http_url: str) -> bool:
    """Push the preview URL into a running editor via its CLI.

    Returns True on apparent success (CLI found and launched), False
    otherwise. Failures are non-fatal — the user always has the plain
    http URL to fall back on.
    """
    cli = shutil.which(editor.cli)
    if not cli:
        print(
            "  note: {} CLI ({!r}) not on PATH; skipping auto-open.".format(
                editor.name, editor.cli,
            ),
            file=sys.stderr,
        )
        return False
    uri = editor_preview_uri(editor, http_url)
    try:
        subprocess.Popen(
            [cli, "--open-url", uri],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except OSError as exc:
        print(
            "  warning: could not launch {}: {}".format(editor.name, exc),
            file=sys.stderr,
        )
        return False
    return True


def open_in_browser(http_url: str) -> bool:
    """Open `http_url` in the user's default web browser.

    Returns True if the stdlib opener thinks it succeeded. Failures are
    non-fatal; the URL is always printed.
    """
    try:
        return webbrowser.open(http_url, new=2)
    except webbrowser.Error as exc:
        print(
            "  warning: could not open web browser: {}".format(exc),
            file=sys.stderr,
        )
        return False


# -----------------------------------------------------------------------------
# Entry point
# -----------------------------------------------------------------------------


@dataclass(frozen=True)
class ServeCacheContext:
    """Bundle of state used to plumb a persistent serve-time cache
    snapshot into the inner build loop. Constructed on startup when
    the document takes the implicit-pipeline path; ``None`` otherwise.

    Holds:
      * ``module``: the imported ``serve_cache`` Python module
        (loaded from runfiles). Functions are accessed off the
        module rather than being top-level imports so the template's
        ``from __future__ import annotations`` doesn't force the
        cache code to load when ENABLE_SERVE_CACHE is False.
      * ``layout``: per-document filesystem layout (cache path,
        sentinel, lock).
      * ``spec``: arguments used to invoke
        ``tools/tectonic_populate_cache.py`` when (re-)priming.
    """

    module: object
    layout: object  # serve_cache.CacheLayout
    spec: object    # serve_cache.PrimeSpec


def _build_cache_context(workspace: Path, runfiles: Path) -> ServeCacheContext | None:
    """Bootstrap the serve-time cache context.

    Returns None when:
      * ENABLE_SERVE_CACHE is False (the document has its own
        cache=, or a toolchain bundle is in scope), or
      * Any required runfile path is missing -- which would be a
        rule-authoring bug, but we degrade to the legacy behaviour
        rather than crashing.

    On success this also kicks off the initial prime if no
    snapshot is present yet. The prime is lock-protected, so
    multiple concurrent serves of the same document play nice.
    """
    if not ENABLE_SERVE_CACHE:
        return None

    serve_cache_path = runfiles / SERVE_CACHE_RUNFILE
    if not serve_cache_path.is_file():
        sys.stderr.write(
            f"latex_serve_web: serve_cache.py missing from runfiles at "
            f"{serve_cache_path}; falling back to implicit pipeline (slow).\n",
        )
        return None

    # Load the cache manager as a module from runfiles. We use
    # importlib so the path is dynamic (it lives under the
    # generated launcher's runfiles dir, which we don't know at
    # template-expansion time).
    import importlib.util

    spec = importlib.util.spec_from_file_location("serve_cache", serve_cache_path)
    if spec is None or spec.loader is None:
        sys.stderr.write(
            f"latex_serve_web: failed to load serve_cache.py from {serve_cache_path}; "
            "falling back to implicit pipeline (slow).\n",
        )
        return None
    serve_cache = importlib.util.module_from_spec(spec)
    # Install in sys.modules BEFORE exec_module: Python 3.12+'s
    # @dataclass decorator looks up the host module via
    # sys.modules to resolve forward type references, and crashes
    # with AttributeError on NoneType if the module isn't there.
    sys.modules["serve_cache"] = serve_cache
    spec.loader.exec_module(serve_cache)

    # Resolve runfile paths to absolute paths for tools, but pass
    # document-source paths as workspace-relative strings (which
    # for sources owned by the main workspace is exactly the
    # short_path).
    tectonic_path = runfiles / PRIME_TECTONIC_RUNFILE
    populate_tool_path = runfiles / PRIME_POPULATE_TOOL_RUNFILE
    biber_path = runfiles / PRIME_BIBER_RUNFILE if PRIME_BIBER_RUNFILE else None
    # Document main path: the short_path for a source owned by the
    # main workspace is the same as the workspace-relative path.
    # (Cross-repo main files are filtered out at rule-analysis
    # time; see latex_serve_web.bzl.)
    main_ws_rel = PRIME_MAIN_RUNFILE

    srcs: list[str] = []
    for rel in PRIME_SRCS_RAW.splitlines():
        rel = rel.strip()
        if not rel:
            continue
        srcs.append(rel)

    pkg_files: list[tuple[str, str]] = []
    for line in PRIME_PKG_FILES_RAW.splitlines():
        line = line.strip()
        if not line or "=" not in line:
            continue
        src_raw, rel_raw = line.split("=", 1)
        pkg_files.append((src_raw, rel_raw))

    prime_spec = serve_cache.PrimeSpec(
        tectonic=tectonic_path,
        populate_tool=populate_tool_path,
        main=main_ws_rel,
        srcs=tuple(srcs),
        pkg_files=tuple(pkg_files),
        biber=biber_path,
        use_system_biber=PRIME_USE_SYSTEM_BIBER,
    )

    layout = serve_cache.derive_cache_layout(workspace, DOCUMENT_LABEL)

    # QoL: keep .cache/rules_latex out of users' git index.
    serve_cache.ensure_gitignore_excludes_cache(workspace)

    if not serve_cache.is_primed(layout):
        try:
            serve_cache.run_prime(layout, prime_spec, workspace)
        except serve_cache.PrimeFailure as e:
            sys.stderr.write(
                "latex_serve_web: initial serve-cache prime failed "
                f"(exit code {e.returncode}). Falling back to the "
                "implicit pipeline (per-edit online prime). The "
                "live-preview will still work but rebuilds will be "
                "slow until this is fixed.\n",
            )
            return None

    return ServeCacheContext(
        module=serve_cache,
        layout=layout,
        spec=prime_spec,
    )


@dataclass(frozen=True)
class PdfChunksContext:
    """Bundle of state used to compute and serve content-addressed
    PDF chunks. Constructed once on startup; may be ``None`` if
    the chunker module can't be loaded (in which case the server
    silently falls back to serving the whole PDF every time).

    Holds:
      * ``module``: the imported ``pdf_chunks`` Python module
        (loaded from runfiles).
      * ``chunks_dir``: per-document directory under
        ``$BUILD_WORKSPACE_DIRECTORY/.cache/rules_latex/<slug>/chunks/``
        where the chunk files are written. Persists across serve
        sessions so a freshly-started serve immediately benefits
        from chunks computed by the previous session.

    The directory is independent of ``ServeCacheContext.layout``
    even though it lives under the same parent: chunks apply to
    *every* document type (implicit-pipeline, ``cache=``, toolchain
    bundle), while the serve cache only applies to the implicit
    pipeline.
    """

    module: object
    chunks_dir: Path


def _build_pdf_chunks_context(
    workspace: Path,
    runfiles: Path,
) -> PdfChunksContext | None:
    """Load ``tools/pdf_chunks.py`` from runfiles and prepare the
    per-document chunks directory.

    Returns ``None`` if the module can't be loaded for any reason.
    Server falls back to whole-PDF transport in that case — every
    save still triggers a build and the browser reloads the full
    PDF; the user just doesn't get the chunking optimization.
    """
    chunks_lib = runfiles / PDF_CHUNKS_RUNFILE
    if not chunks_lib.is_file():
        sys.stderr.write(
            "latex_serve_web: pdf_chunks.py missing from runfiles at "
            f"{chunks_lib}; the PDF will be re-sent in full on every "
            "rebuild.\n",
        )
        return None

    import importlib.util

    spec = importlib.util.spec_from_file_location("pdf_chunks", chunks_lib)
    if spec is None or spec.loader is None:
        sys.stderr.write(
            "latex_serve_web: failed to import pdf_chunks.py; "
            "falling back to whole-PDF transport.\n",
        )
        return None
    module = importlib.util.module_from_spec(spec)
    sys.modules["pdf_chunks"] = module
    try:
        spec.loader.exec_module(module)
    except Exception as e:
        sys.stderr.write(
            f"latex_serve_web: pdf_chunks.py exec failed: {e}; "
            "falling back to whole-PDF transport.\n",
        )
        return None

    # Derive the chunks directory: same slug as serve_cache uses,
    # but always under .cache/rules_latex/<slug>/chunks/ regardless
    # of whether the serve cache is active. Slug derivation is
    # duplicated here from serve_cache._slugify_label rather than
    # taking a runtime dependency on serve_cache (which is itself
    # conditionally loaded).
    import hashlib
    import re as _re

    stripped = DOCUMENT_LABEL.lstrip("@/")
    if stripped.startswith("@"):
        stripped = stripped.lstrip("@")
    if "//" in stripped:
        _, _, stripped = stripped.partition("//")
    sanitised = _re.sub(r"[^A-Za-z0-9_.-]", "_", stripped.replace(":", "_"))
    digest = hashlib.sha1(DOCUMENT_LABEL.encode("utf-8")).hexdigest()[:6]
    slug = f"{sanitised}_{digest}"
    chunks_dir = workspace / ".cache" / "rules_latex" / slug / "chunks"
    try:
        chunks_dir.mkdir(parents=True, exist_ok=True)
    except OSError as e:
        sys.stderr.write(
            f"latex_serve_web: could not create chunks dir "
            f"{chunks_dir}: {e}; falling back to whole-PDF transport.\n",
        )
        return None

    return PdfChunksContext(module=module, chunks_dir=chunks_dir)


# Age (seconds) below which a chunk is considered "fresh" and not
# eligible for GC even if it isn't in the current manifest. Lets
# the user undo a recent edit without re-fetching the body chunk
# that just got removed from the manifest.
_CHUNK_GC_MIN_AGE_SECONDS = 5 * 60


def _gc_chunks(
    chunks_dir: Path,
    keep_hashes: set,
    *,
    min_age_seconds: float = _CHUNK_GC_MIN_AGE_SECONDS,
) -> int:
    """Delete chunk files not in ``keep_hashes`` and older than
    ``min_age_seconds``. Returns the number of files deleted.

    Safe to call from the watcher thread after each successful
    build. The min-age guard prevents thrashing when the user is
    rapidly alternating between two versions of a document
    (chunks just removed from the manifest will be re-added on
    the next save).
    """
    deleted = 0
    cutoff = time.time() - min_age_seconds
    try:
        for entry in chunks_dir.iterdir():
            if not entry.is_file():
                continue
            name = entry.name
            # Defensive: only touch files that look like SHA-256
            # hex hashes. Skip the .tmp atomic-write sidecars and
            # anything else.
            if len(name) != 64 or not all(
                c in "0123456789abcdef" for c in name
            ):
                continue
            if name in keep_hashes:
                continue
            try:
                st = entry.stat()
            except OSError:
                continue
            if st.st_mtime > cutoff:
                continue
            try:
                entry.unlink()
                deleted += 1
            except OSError:
                pass
    except OSError:
        # chunks_dir may have been removed externally; ignore.
        pass
    return deleted


def _compute_manifest_post_build(
    state: BuildState,
    workspace: Path,
    pdf_chunks_ctx: PdfChunksContext | None,
) -> None:
    """Hook called from the watcher after each successful build.

    Computes the chunk manifest for the freshly-produced PDF,
    installs it on ``state``, and GCs stale chunks. Failures here
    are non-fatal: the browser falls back to whole-PDF transport
    automatically when the manifest is absent.
    """
    if pdf_chunks_ctx is None:
        return
    pdf_path = workspace / "bazel-bin" / PDF_RELPATH
    if not pdf_path.is_file():
        # Build "succeeded" but the PDF wasn't produced where we
        # expected — likely a non-pdf outfmt (xdv/html/aux). The
        # chunk manifest doesn't apply.
        state.update_manifest(None)
        return
    try:
        manifest = pdf_chunks_ctx.module.compute_manifest(
            pdf_path,
            pdf_chunks_ctx.chunks_dir,
        )
    except Exception as e:
        # The parser is designed never to raise — it returns None
        # on any parse failure. If we get here it's a real bug
        # (e.g. OOM, IO error). Log and continue with no manifest.
        sys.stderr.write(
            f"latex_serve_web: PDF chunker raised unexpectedly: {e}; "
            "browser will fall back to whole-PDF transport.\n",
        )
        state.update_manifest(None)
        return
    state.update_manifest(manifest)
    if manifest is not None:
        keep = {c.hash for c in manifest.chunks}
        _gc_chunks(pdf_chunks_ctx.chunks_dir, keep)


def main() -> int:
    if len(sys.argv) < 3:
        print(
            "usage: serve_web.py <workspace_dir> <runfiles_dir>",
            file=sys.stderr,
        )
        return 2
    workspace = Path(sys.argv[1]).resolve()
    runfiles = Path(sys.argv[2]).resolve()
    if not workspace.is_dir():
        print(f"ERROR: workspace {workspace} is not a directory.", file=sys.stderr)
        return 2
    if not runfiles.is_dir():
        print(f"ERROR: runfiles {runfiles} is not a directory.", file=sys.stderr)
        return 2

    # Read the vendored PDF.js files once at startup so per-request
    # serving is a fast in-memory copy. The launcher script puts both
    # files into our runfiles tree.
    pdfjs_lib_path = runfiles / PDFJS_LIB_RUNFILE
    pdfjs_worker_path = runfiles / PDFJS_WORKER_RUNFILE
    if not pdfjs_lib_path.is_file():
        print(
            f"ERROR: vendored pdfjs file missing at {pdfjs_lib_path}; "
            "did the @rules_latex_pdfjs repo fail to materialise?",
            file=sys.stderr,
        )
        return 2
    if not pdfjs_worker_path.is_file():
        print(
            f"ERROR: vendored pdfjs worker missing at {pdfjs_worker_path}.",
            file=sys.stderr,
        )
        return 2

    # Bootstrap the serve-time cache override (no-op for documents
    # with `cache=` or a toolchain bundle). May block for 30-90 s
    # on the first run while priming.
    cache_ctx = _build_cache_context(workspace, runfiles)

    # Load the PDF chunker for content-addressed PDF transfer (see
    # tools/pdf_chunks.py). On any failure to load we fall back to
    # whole-PDF transport silently — chunking is purely an
    # optimization, never a correctness requirement.
    pdf_chunks_ctx = _build_pdf_chunks_context(workspace, runfiles)

    state = BuildState()
    Handler.state = state
    Handler.workspace = workspace
    Handler.pdfjs_lib_bytes = pdfjs_lib_path.read_bytes()
    Handler.pdfjs_worker_bytes = pdfjs_worker_path.read_bytes()
    Handler.pdf_chunks_ctx = pdf_chunks_ctx

    # SO_REUSEADDR lets the user kill+restart the serve target quickly
    # without hitting "Address already in use" while the kernel holds
    # the TIME_WAIT socket. (We're localhost-only, so the usual
    # warnings about REUSEADDR don't apply.)
    ThreadingHTTPServer.allow_reuse_address = True
    server = ThreadingHTTPServer(("127.0.0.1", PORT), Handler)

    print(f"latex_serve_web: serving live preview for {DOCUMENT_LABEL}")
    print(f"  rebuild target: {DOCUMENT_LABEL}")
    print(f"  output pdf:     bazel-bin/{PDF_RELPATH}")
    if cache_ctx is not None:
        print(f"  serve cache:    {cache_ctx.layout.extracted}/")
    if pdf_chunks_ctx is not None:
        print(f"  chunks cache:   {pdf_chunks_ctx.chunks_dir}/")
    print(
        f"  pdf.js sizes:   lib={len(Handler.pdfjs_lib_bytes)//1024} KiB, "
        f"worker={len(Handler.pdfjs_worker_bytes)//1024} KiB",
    )
    print("  press Ctrl-C to stop.")
    print()

    # URLs are printed *last* so they're the freshest thing on screen
    # when the user comes back to the terminal — and the plain http URL
    # is printed last of all so it's unconditionally available as a
    # fallback. The editor-specific URI (if any) goes just above it.
    http_url = f"http://127.0.0.1:{PORT}/"
    editor = detect_editor()
    if editor is not None:
        print(f"  detected {editor.name} terminal; preview URLs:")
        print(
            f"    open in {editor.name} (Simple Browser): "
            f"{editor_preview_uri(editor, http_url)}"
        )
        print(f"    open in browser:                       {http_url}")
    else:
        print(f"  preview URL: {http_url}")
    print()

    if OPEN_ON_START:
        if editor is not None:
            if open_in_editor(editor, http_url):
                print(f"  → opened in {editor.name}.")
            else:
                # Editor CLI not available; fall back to the system
                # browser so open_on_start still does *something*.
                if open_in_browser(http_url):
                    print("  → opened in default web browser.")
        else:
            if open_in_browser(http_url):
                print("  → opened in default web browser.")
        print()

    watcher = threading.Thread(
        target=watcher_loop,
        args=(workspace, state, cache_ctx, pdf_chunks_ctx),
        daemon=True,
        name="latex-serve-watcher",
    )
    watcher.start()

    signal.signal(signal.SIGINT, lambda *_: sys.exit(0))
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    return 0


if __name__ == "__main__":
    sys.exit(main())
