#!/usr/bin/env python3
"""Browser-based live preview server for a LaTeX document.

Generated by the `latex_serve_web` Bazel rule. Don't edit by hand;
edit //latex/private:serve_web.py.tpl instead.

What this is:

* A tiny HTTP server (Python stdlib's http.server) running on
  localhost.
* GET /          -> a single-page HTML wrapper that loads PDF.js from
                    a CDN, renders the current PDF in a canvas, and
                    listens for reload events on /events.
* GET /pdf       -> serves the bytes of bazel-bin/<doc>.pdf.
* GET /events    -> Server-Sent Events stream; emits 'data: reload\\n\\n'
                    every time a rebuild finishes successfully.
* GET /status    -> JSON status of the last build (success, elapsed,
                    timestamp). Used by the page to display compile
                    state ("building...", "✓ built in 0.4s").

Background thread polls the watched source files at POLL_INTERVAL_MS
intervals and runs `bazel build` on every detected change, the same
way `latex_serve` does. On success it bumps a counter and pings every
connected SSE listener.

No third-party Python deps. PDF.js is pulled from
cdn.jsdelivr.net at page-load time — the rule deliberately doesn't
vendor a ~3 MB JS bundle. Users without internet at preview-time can
fall back to `latex_serve` (system viewer).
"""

from __future__ import annotations

import json
import queue
import signal
import subprocess
import sys
import threading
import time
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

# Filled in by `latex_serve_web`:
DOCUMENT_LABEL = "{{DOCUMENT_LABEL}}"
PDF_RELPATH = "{{PDF_RELPATH}}"
WATCHED_PATHS_RAW = """\
{{WATCHED_PATHS}}"""
POLL_INTERVAL_MS = int("{{POLL_INTERVAL}}")
PORT = int("{{PORT}}")
DOCUMENT_NAME = "{{DOCUMENT_NAME}}"

# Paths to the vendored PDF.js files within the launcher's runfiles
# tree. The server reads them once on startup and serves the bytes at
# /_pdfjs/pdf.mjs and /_pdfjs/pdf.worker.mjs.
PDFJS_LIB_RUNFILE = "{{PDFJS_LIB_RUNFILE}}"
PDFJS_WORKER_RUNFILE = "{{PDFJS_WORKER_RUNFILE}}"

# Browser-side URLs for the same files. Centralised so the HTML
# template is just a format string.
PDFJS_LIB = "/_pdfjs/pdf.mjs"
PDFJS_WORKER = "/_pdfjs/pdf.worker.mjs"


# -----------------------------------------------------------------------------
# Build state
# -----------------------------------------------------------------------------


class BuildState:
    """Thread-safe shared state between the watcher and HTTP handlers.

    The HTTP server hands out an SSE listener queue per connected
    client, plus a `current` snapshot for /status responses. The
    watcher pushes a `tick` to every queue on every successful build;
    handlers translate that into an SSE message.
    """

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._listeners: list[queue.Queue[str]] = []
        self._build_count: int = 0
        self._last_success: bool = False
        self._last_elapsed: float = 0.0
        self._last_finished_at: float = 0.0
        self._last_message: str = "starting up..."

    def add_listener(self) -> "queue.Queue[str]":
        q: queue.Queue[str] = queue.Queue(maxsize=8)
        with self._lock:
            self._listeners.append(q)
        return q

    def drop_listener(self, q: "queue.Queue[str]") -> None:
        with self._lock:
            if q in self._listeners:
                self._listeners.remove(q)

    def record_build(self, success: bool, elapsed: float, message: str) -> None:
        with self._lock:
            self._build_count += 1
            self._last_success = success
            self._last_elapsed = elapsed
            self._last_finished_at = time.time()
            self._last_message = message
            listeners = list(self._listeners)
        # Notify outside the lock so a slow listener can't block the
        # build thread for more than the per-queue timeout.
        event = "reload" if success else "build-failed"
        for q in listeners:
            try:
                q.put(event, timeout=0.1)
            except queue.Full:
                # Slow listener; drop it. It can reconnect.
                pass

    def snapshot(self) -> dict[str, object]:
        with self._lock:
            return {
                "build_count": self._build_count,
                "last_success": self._last_success,
                "last_elapsed_seconds": round(self._last_elapsed, 3),
                "last_finished_at": self._last_finished_at,
                "last_message": self._last_message,
            }


# -----------------------------------------------------------------------------
# Watcher
# -----------------------------------------------------------------------------


def snapshot_mtimes(paths: list[Path]) -> dict[Path, float]:
    """Stat every watched path; missing files contribute 0.0."""
    result: dict[Path, float] = {}
    for path in paths:
        try:
            result[path] = path.stat().st_mtime_ns
        except FileNotFoundError:
            result[path] = 0.0
    return result


def run_bazel_build(workspace: Path) -> tuple[bool, float, str]:
    """Run `bazel build <DOCUMENT_LABEL>` from the workspace root.

    Returns (success, elapsed_seconds, summary_message).
    """
    start = time.monotonic()
    cmd = [
        "bazel",
        "build",
        "--watchfs",
        "--noshow_progress",
        DOCUMENT_LABEL,
    ]
    try:
        result = subprocess.run(
            cmd,
            cwd=workspace,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        return (
            False,
            time.monotonic() - start,
            "ERROR: bazel not found on PATH",
        )
    elapsed = time.monotonic() - start
    if result.returncode == 0:
        return (True, elapsed, f"built in {elapsed:.2f}s")
    # Surface stderr to the operator's console; the browser only sees
    # the summary string.
    sys.stderr.write(result.stderr)
    sys.stderr.flush()
    return (False, elapsed, f"BUILD FAILED ({elapsed:.2f}s)")


def watcher_loop(workspace: Path, state: BuildState) -> None:
    """Background thread: detect source changes, run bazel build."""
    watched_paths = [
        workspace / rel
        for rel in WATCHED_PATHS_RAW.splitlines()
        if rel.strip()
    ]
    interval = POLL_INTERVAL_MS / 1000.0

    # Initial build so the first browser page-load has something to
    # display.
    success, elapsed, msg = run_bazel_build(workspace)
    print(f"latex_serve_web: initial build: {msg}", flush=True)
    state.record_build(success, elapsed, msg)

    last_mtimes = snapshot_mtimes(watched_paths)
    while True:
        time.sleep(interval)
        current = snapshot_mtimes(watched_paths)
        changed = [p for p, m in current.items() if m != last_mtimes.get(p, 0.0)]
        if not changed:
            continue
        last_mtimes = current

        rels = ", ".join(str(p.relative_to(workspace)) for p in changed)
        ts = time.strftime("%H:%M:%S")
        print(f"[{ts}] changed: {rels}", flush=True)
        success, elapsed, msg = run_bazel_build(workspace)
        print(f"  {msg}", flush=True)
        state.record_build(success, elapsed, msg)


# -----------------------------------------------------------------------------
# HTTP handlers
# -----------------------------------------------------------------------------


INDEX_HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{document_name} – live preview</title>
<style>
  * {{ box-sizing: border-box; }}
  body {{
    font: 13px/1.4 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    margin: 0; background: #2b2b2b; color: #e8e8e8;
    display: grid; grid-template-rows: auto 1fr;
    height: 100vh;
  }}
  header {{
    display: flex; gap: 12px; align-items: center;
    padding: 8px 12px; background: #1d1d1d;
    border-bottom: 1px solid #000;
  }}
  header h1 {{
    margin: 0; font-size: 13px; font-weight: 600;
    letter-spacing: 0.02em;
  }}
  #status {{
    margin-left: auto; padding: 3px 9px; border-radius: 4px;
    font-variant-numeric: tabular-nums;
    transition: background 0.2s;
  }}
  #status.ok      {{ background: #1e3a1e; color: #b4f0b4; }}
  #status.fail    {{ background: #4a1818; color: #ffb4b4; }}
  #status.building {{ background: #3a3a1e; color: #f0f0b4; }}
  #status.idle    {{ background: #333; color: #aaa; }}
  #zoom-controls {{ display: flex; gap: 6px; }}
  #zoom-controls button {{
    background: #333; color: #e8e8e8; border: 1px solid #555;
    padding: 3px 9px; border-radius: 4px; font: inherit; cursor: pointer;
  }}
  #zoom-controls button:hover {{ background: #444; }}
  #viewer {{
    overflow: auto; padding: 16px; background: #2b2b2b;
    text-align: center;
  }}
  #viewer canvas {{
    display: block; margin: 0 auto 12px; background: white;
    box-shadow: 0 2px 8px rgba(0,0,0,0.4);
  }}
  #empty {{ color: #888; padding: 32px; }}
</style>
</head>
<body>
<header>
  <h1>{document_name}</h1>
  <div id="zoom-controls">
    <button id="zoom-out" title="Zoom out">−</button>
    <button id="zoom-reset" title="Reset zoom">100%</button>
    <button id="zoom-in" title="Zoom in">+</button>
  </div>
  <div id="status" class="idle">connecting…</div>
</header>
<div id="viewer"><div id="empty">waiting for first build…</div></div>

<script type="module">
import * as pdfjsLib from "{pdfjs_lib}";
pdfjsLib.GlobalWorkerOptions.workerSrc = "{pdfjs_worker}";

const viewer = document.getElementById("viewer");
const statusEl = document.getElementById("status");
let currentDoc = null;
let scale = 1.5;

const fmt = (n) => Number(n).toFixed(2);

function setStatus(cls, text) {{
  statusEl.className = cls;
  statusEl.textContent = text;
}}

async function renderDocument(url) {{
  setStatus("building", "rendering…");
  // Cache-busting query string forces a fresh fetch; the underlying
  // /pdf endpoint sets Cache-Control: no-store anyway, but some
  // browsers ignore that for explicit reload triggers.
  const bust = Date.now();
  try {{
    const loadingTask = pdfjsLib.getDocument(`${{url}}?t=${{bust}}`);
    const pdf = await loadingTask.promise;
    currentDoc = pdf;
    await renderAllPages(pdf);
  }} catch (err) {{
    setStatus("fail", `render error: ${{err.message || err}}`);
    console.error(err);
  }}
}}

async function renderAllPages(pdf) {{
  // Preserve scroll position across re-renders so editing doesn't
  // bounce the user back to page 1.
  const prevScroll = {{ top: viewer.scrollTop, left: viewer.scrollLeft }};
  const fresh = document.createElement("div");
  for (let i = 1; i <= pdf.numPages; i++) {{
    const page = await pdf.getPage(i);
    const viewport = page.getViewport({{ scale }});
    const canvas = document.createElement("canvas");
    canvas.width = viewport.width;
    canvas.height = viewport.height;
    const ctx = canvas.getContext("2d");
    await page.render({{ canvasContext: ctx, viewport }}).promise;
    fresh.appendChild(canvas);
  }}
  viewer.replaceChildren(fresh);
  viewer.scrollTo(prevScroll);
  // Apply the latest status from the server (race: a new build may
  // have completed during the render).
  await refreshStatus();
}}

async function refreshStatus() {{
  try {{
    const r = await fetch("/status");
    const s = await r.json();
    if (s.last_success) {{
      setStatus("ok", `✓ ${{s.last_message}} · build #${{s.build_count}}`);
    }} else {{
      setStatus("fail", `${{s.last_message}}`);
    }}
  }} catch (e) {{
    setStatus("fail", "server unreachable");
  }}
}}

const evtSrc = new EventSource("/events");
evtSrc.onmessage = (e) => {{
  if (e.data === "reload") {{
    renderDocument("/pdf");
  }} else if (e.data === "build-failed") {{
    refreshStatus();
  }} else if (e.data === "hello") {{
    refreshStatus();
  }}
}};
evtSrc.onerror = () => {{
  setStatus("fail", "lost connection to server");
}};

document.getElementById("zoom-in").addEventListener("click", () => {{
  scale = Math.min(scale * 1.2, 4.0);
  if (currentDoc) renderAllPages(currentDoc);
}});
document.getElementById("zoom-out").addEventListener("click", () => {{
  scale = Math.max(scale / 1.2, 0.4);
  if (currentDoc) renderAllPages(currentDoc);
}});
document.getElementById("zoom-reset").addEventListener("click", () => {{
  scale = 1.5;
  if (currentDoc) renderAllPages(currentDoc);
}});

// Try once on page load; the SSE 'hello' event will also call this
// once the connection is up.
renderDocument("/pdf");
refreshStatus();
</script>
</body>
</html>
"""


class Handler(BaseHTTPRequestHandler):
    # Class-level attributes set by run_server() before this is used.
    state: BuildState
    workspace: Path
    pdfjs_lib_bytes: bytes
    pdfjs_worker_bytes: bytes

    def log_message(self, format: str, *args: object) -> None:  # noqa: A002
        # http.server is chatty by default; we already log builds
        # ourselves from the watcher thread. Suppress per-request lines.
        return

    def _send(
        self,
        status: int,
        body: bytes,
        content_type: str,
        extra_headers: dict[str, str] | None = None,
    ) -> None:
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        for k, v in (extra_headers or {}).items():
            self.send_header(k, v)
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self) -> None:  # noqa: N802 (http.server API)
        path = self.path.split("?", 1)[0]
        if path == "/":
            html = INDEX_HTML_TEMPLATE.format(
                document_name=DOCUMENT_NAME,
                pdfjs_lib=PDFJS_LIB,
                pdfjs_worker=PDFJS_WORKER,
            )
            self._send(HTTPStatus.OK, html.encode("utf-8"), "text/html; charset=utf-8")
            return
        if path == "/pdf":
            pdf_path = self.workspace / "bazel-bin" / PDF_RELPATH
            try:
                body = pdf_path.read_bytes()
            except FileNotFoundError:
                self._send(
                    HTTPStatus.NOT_FOUND,
                    b"PDF not built yet.",
                    "text/plain; charset=utf-8",
                )
                return
            self._send(HTTPStatus.OK, body, "application/pdf")
            return
        if path == "/_pdfjs/pdf.mjs":
            # ESM Javascript MIME type per the WHATWG fetch spec.
            self._send(
                HTTPStatus.OK,
                self.pdfjs_lib_bytes,
                "text/javascript; charset=utf-8",
            )
            return
        if path == "/_pdfjs/pdf.worker.mjs":
            self._send(
                HTTPStatus.OK,
                self.pdfjs_worker_bytes,
                "text/javascript; charset=utf-8",
            )
            return
        if path == "/status":
            body = json.dumps(self.state.snapshot()).encode("utf-8")
            self._send(HTTPStatus.OK, body, "application/json")
            return
        if path == "/events":
            self._stream_events()
            return
        self._send(
            HTTPStatus.NOT_FOUND,
            b"not found",
            "text/plain; charset=utf-8",
        )

    def _stream_events(self) -> None:
        self.send_response(HTTPStatus.OK)
        self.send_header("Content-Type", "text/event-stream")
        self.send_header("Cache-Control", "no-store")
        self.send_header("Connection", "keep-alive")
        # Allow same-origin only; we only ever bind to localhost so
        # this is mostly belt-and-braces.
        self.send_header("X-Accel-Buffering", "no")
        self.end_headers()

        q = self.state.add_listener()
        try:
            # Send a hello so the page knows the connection is live.
            self.wfile.write(b"data: hello\n\n")
            self.wfile.flush()

            # 15s keepalive so proxies (and python http.server's own
            # connection-handling) don't close the stream during quiet
            # periods.
            keepalive_interval = 15.0
            last_send = time.monotonic()
            while True:
                try:
                    event = q.get(timeout=1.0)
                    self.wfile.write(f"data: {event}\n\n".encode("utf-8"))
                    self.wfile.flush()
                    last_send = time.monotonic()
                except queue.Empty:
                    if time.monotonic() - last_send > keepalive_interval:
                        self.wfile.write(b": keepalive\n\n")
                        self.wfile.flush()
                        last_send = time.monotonic()
        except (BrokenPipeError, ConnectionResetError):
            pass
        finally:
            self.state.drop_listener(q)


# -----------------------------------------------------------------------------
# Entry point
# -----------------------------------------------------------------------------


def main() -> int:
    if len(sys.argv) < 3:
        print(
            "usage: serve_web.py <workspace_dir> <runfiles_dir>",
            file=sys.stderr,
        )
        return 2
    workspace = Path(sys.argv[1]).resolve()
    runfiles = Path(sys.argv[2]).resolve()
    if not workspace.is_dir():
        print(f"ERROR: workspace {workspace} is not a directory.", file=sys.stderr)
        return 2
    if not runfiles.is_dir():
        print(f"ERROR: runfiles {runfiles} is not a directory.", file=sys.stderr)
        return 2

    # Read the vendored PDF.js files once at startup so per-request
    # serving is a fast in-memory copy. The launcher script puts both
    # files into our runfiles tree.
    pdfjs_lib_path = runfiles / PDFJS_LIB_RUNFILE
    pdfjs_worker_path = runfiles / PDFJS_WORKER_RUNFILE
    if not pdfjs_lib_path.is_file():
        print(
            f"ERROR: vendored pdfjs file missing at {pdfjs_lib_path}; "
            "did the @rules_latex_pdfjs repo fail to materialise?",
            file=sys.stderr,
        )
        return 2
    if not pdfjs_worker_path.is_file():
        print(
            f"ERROR: vendored pdfjs worker missing at {pdfjs_worker_path}.",
            file=sys.stderr,
        )
        return 2

    state = BuildState()
    Handler.state = state
    Handler.workspace = workspace
    Handler.pdfjs_lib_bytes = pdfjs_lib_path.read_bytes()
    Handler.pdfjs_worker_bytes = pdfjs_worker_path.read_bytes()

    # SO_REUSEADDR lets the user kill+restart the serve target quickly
    # without hitting "Address already in use" while the kernel holds
    # the TIME_WAIT socket. (We're localhost-only, so the usual
    # warnings about REUSEADDR don't apply.)
    ThreadingHTTPServer.allow_reuse_address = True
    server = ThreadingHTTPServer(("127.0.0.1", PORT), Handler)

    print(f"latex_serve_web: serving live preview at http://127.0.0.1:{PORT}/")
    print(f"  rebuild target: {DOCUMENT_LABEL}")
    print(f"  output pdf:     bazel-bin/{PDF_RELPATH}")
    print(
        f"  pdf.js sizes:   lib={len(Handler.pdfjs_lib_bytes)//1024} KiB, "
        f"worker={len(Handler.pdfjs_worker_bytes)//1024} KiB",
    )
    print("  press Ctrl-C to stop.")
    print()

    watcher = threading.Thread(
        target=watcher_loop,
        args=(workspace, state),
        daemon=True,
        name="latex-serve-watcher",
    )
    watcher.start()

    signal.signal(signal.SIGINT, lambda *_: sys.exit(0))
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    return 0


if __name__ == "__main__":
    sys.exit(main())
