#!/usr/bin/env python3
"""Watch a LaTeX document's sources and rebuild on every save.

Generated by the `latex_serve` Bazel rule. Don't edit by hand; edit
//latex/private:serve_watcher.py.tpl instead.

Design notes:

* The watcher is pure-stdlib so it works on any Python 3.8+ environment
  without taking a `rules_python` or `watchdog` dependency. Pure stat
  polling is plenty fast for the editor-save cadence we care about.

* Rebuilds shell out to `bazel build <document_label>` rather than
  invoking tectonic directly. This means rebuilds use the same toolchain,
  sandbox, env, and cache as a regular `bazel build` — no
  "works-on-my-machine" surprises versus CI.

* The PDF viewer is opened once on first successful build. Subsequent
  rebuilds rely on the viewer's own auto-reload (macOS Preview, Linux
  Evince/Okular do this; Windows viewers vary).
"""

from __future__ import annotations

import os
import shutil
import signal
import subprocess
import sys
import time
from pathlib import Path

# Filled in by `latex_serve`:
DOCUMENT_LABEL = "{{DOCUMENT_LABEL}}"
PDF_RELPATH = "{{PDF_RELPATH}}"
WATCHED_PATHS_RAW = """\
{{WATCHED_PATHS}}"""
POLL_INTERVAL_MS = int("{{POLL_INTERVAL}}")
OPEN_PDF = bool(int("{{OPEN_PDF}}"))


def snapshot_mtimes(paths: list[Path]) -> dict[Path, float]:
    """Stat every watched path; missing files contribute 0.0.

    We treat "missing" as a sentinel rather than an error so the watcher
    tolerates files appearing and disappearing during edits (some
    editors do atomic-rename saves: the file briefly doesn't exist).
    """
    result: dict[Path, float] = {}
    for path in paths:
        try:
            result[path] = path.stat().st_mtime_ns
        except FileNotFoundError:
            result[path] = 0.0
    return result


def open_in_viewer(pdf: Path) -> None:
    """Open ``pdf`` in the system default viewer if available.

    Failures are non-fatal — the build still ran, the user can open
    the file themselves.
    """
    candidates = []
    if sys.platform == "darwin":
        candidates.append(["open", str(pdf)])
    elif sys.platform.startswith("linux"):
        candidates.append(["xdg-open", str(pdf)])
    elif sys.platform == "win32":
        candidates.append(["cmd", "/c", "start", "", str(pdf)])

    for cmd in candidates:
        binary = cmd[0]
        if not shutil.which(binary):
            continue
        try:
            subprocess.Popen(
                cmd,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            print(f"  opened {pdf} in {binary}")
            return
        except OSError as exc:
            print(f"  warning: could not run {binary}: {exc}", file=sys.stderr)
    print(
        f"  warning: no PDF viewer command found; open {pdf} manually.",
        file=sys.stderr,
    )


def run_bazel_build(workspace: Path) -> tuple[bool, float]:
    """Run `bazel build <DOCUMENT_LABEL>` from the workspace root.

    Returns (success, elapsed_seconds).

    A few flags worth calling out:

    * ``--watchfs`` tells Bazel to use inotify/fsevents on Linux/macOS
      to detect changes instead of re-stating every file. Cuts the
      "no-op rebuild" latency on cold cache from ~300ms to ~80ms.

    * ``--noshow_progress`` keeps the watcher's log readable — Bazel's
      progress chatter is otherwise mixed in with our own build-step
      messages.
    """
    start = time.monotonic()
    cmd = [
        "bazel",
        "build",
        "--watchfs",
        "--noshow_progress",
        DOCUMENT_LABEL,
    ]
    try:
        result = subprocess.run(cmd, cwd=workspace)
    except FileNotFoundError:
        print(
            "ERROR: 'bazel' not found on PATH; latex_serve needs to be able "
            "to invoke bazel from within the workspace.",
            file=sys.stderr,
        )
        return (False, time.monotonic() - start)
    elapsed = time.monotonic() - start
    return (result.returncode == 0, elapsed)


def main() -> int:
    if len(sys.argv) < 2:
        print("usage: serve_watcher.py <workspace_dir>", file=sys.stderr)
        return 2
    workspace = Path(sys.argv[1]).resolve()
    if not workspace.is_dir():
        print(f"ERROR: workspace {workspace} is not a directory.", file=sys.stderr)
        return 2

    watched_paths = [
        workspace / rel
        for rel in WATCHED_PATHS_RAW.splitlines()
        if rel.strip()
    ]
    if not watched_paths:
        print(
            "WARNING: latex_serve has no watchable sources. This usually "
            "means the document's LatexInfo only references files from "
            "external repositories. Edits won't trigger rebuilds.",
            file=sys.stderr,
        )

    # bazel-bin is a workspace-relative symlink that always points at
    # the active build's output tree.
    pdf_path = workspace / "bazel-bin" / PDF_RELPATH

    print(f"latex_serve: watching {len(watched_paths)} file(s):")
    for p in watched_paths:
        print(f"  - {p.relative_to(workspace)}")
    print(f"  rebuild target: {DOCUMENT_LABEL}")
    print(f"  output pdf:     bazel-bin/{PDF_RELPATH}")
    print("  press Ctrl-C to stop.")
    print()

    # Build immediately on startup so the user has a fresh PDF.
    success, elapsed = run_bazel_build(workspace)
    if success:
        print(f"  built in {elapsed:.2f}s")
        if OPEN_PDF and pdf_path.exists():
            open_in_viewer(pdf_path)
    else:
        print(f"  build FAILED after {elapsed:.2f}s; will retry on next change.")
    print()

    last_mtimes = snapshot_mtimes(watched_paths)
    interval = POLL_INTERVAL_MS / 1000.0

    # Allow Ctrl-C to exit cleanly.
    signal.signal(signal.SIGINT, lambda *_: sys.exit(0))

    while True:
        time.sleep(interval)
        current = snapshot_mtimes(watched_paths)
        changed = [p for p, m in current.items() if m != last_mtimes.get(p, 0.0)]
        if not changed:
            continue

        last_mtimes = current
        ts = time.strftime("%H:%M:%S")
        for p in changed:
            print(f"[{ts}] changed: {p.relative_to(workspace)}")
        success, elapsed = run_bazel_build(workspace)
        if success:
            print(f"  built in {elapsed:.2f}s")
        else:
            print(f"  build FAILED after {elapsed:.2f}s")
        print()


if __name__ == "__main__":
    sys.exit(main())
