module(name = "rules_latex_python_314_consumer")

bazel_dep(name = "rules_latex", version = "0.6.1")
bazel_dep(name = "rules_python", version = "2.3.2")

local_path_override(
    module_name = "rules_latex",
    path = "../../..",
)

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(python_version = "3.14")
