"""Unit tests for the SyncTeX parser embedded in serve_web.py.tpl.

The parser lives inside the template so it can be shipped as a
single-file Python module by latex_serve_web. To test it without
shipping the template-substitution machinery, we load the template,
substitute placeholders with safe defaults, and import the result.
"""

from __future__ import annotations

import gzip
import importlib.util
import sys
import tempfile
import unittest
from pathlib import Path


_TEMPLATE_PATH = (
    Path(__file__).resolve().parent.parent.parent
    / "latex"
    / "private"
    / "serve_web.py.tpl"
)
_PLACEHOLDERS = {
    "{{DOCUMENT_LABEL}}": "//test:doc",
    "{{PDF_RELPATH}}": "test/doc.pdf",
    "{{SYNCTEX_RELPATH}}": "test/doc.synctex.gz",
    "{{WATCHED_PATHS}}": "test/doc.tex",
    "{{POLL_INTERVAL}}": "250",
    "{{DEBOUNCE_MS}}": "250",
    "{{DEBOUNCE_MAX_MS}}": "1500",
    "{{PORT}}": "8765",
    "{{DOCUMENT_NAME}}": "doc",
    "{{PDFJS_LIB_RUNFILE}}": "_pdfjs/pdf.mjs",
    "{{PDFJS_WORKER_RUNFILE}}": "_pdfjs/pdf.worker.mjs",
    "{{OPEN_ON_START}}": "0",
    # Serve-cache plumbing (covered separately by test_serve_cache).
    # Empty values exercise the disabled-cache branch in the template.
    "{{ENABLE_SERVE_CACHE}}": "",
    "{{SERVE_CACHE_RUNFILE}}": "",
    "{{PRIME_MAIN_RUNFILE}}": "",
    "{{PRIME_TECTONIC_RUNFILE}}": "",
    "{{PRIME_POPULATE_TOOL_RUNFILE}}": "",
    "{{PRIME_STAGING_LIB_RUNFILE}}": "",
    "{{PRIME_BIBER_RUNFILE}}": "",
    "{{PRIME_USE_SYSTEM_BIBER}}": "",
    "{{PRIME_SRCS}}": "",
    "{{PRIME_PKG_FILES}}": "",
}


def _load_template_module():
    """Substitute placeholders and import the resulting Python."""
    source = _TEMPLATE_PATH.read_text()
    for placeholder, replacement in _PLACEHOLDERS.items():
        source = source.replace(placeholder, replacement)

    # Write to a real .py file so dataclass introspection of __module__
    # works correctly (it can't if we just exec the source against
    # ad-hoc globals).
    tmp = tempfile.NamedTemporaryFile(
        mode="w", suffix=".py", delete=False, encoding="utf-8"
    )
    try:
        tmp.write(source)
        tmp.close()
        spec = importlib.util.spec_from_file_location(
            "serve_web_test_module", tmp.name
        )
        module = importlib.util.module_from_spec(spec)
        sys.modules["serve_web_test_module"] = module
        spec.loader.exec_module(module)
        return module
    finally:
        Path(tmp.name).unlink()


_M = _load_template_module()


# A minimal SyncTeX file generated by tectonic 0.16.9 for a single-line
# hello-world LaTeX document. Captured from a real compile to keep
# this test reflective of what the parser actually has to handle.
SAMPLE_SYNCTEX = """SyncTeX Version:1
Input:1:/sandbox/exec/_main/hello.tex
Input:4:/sandbox/exec/_main/preamble.tex
Output:pdf
Magnification:1000
Unit:1
X Offset:0
Y Offset:0
Content:
!166
{1
[1,11:4736287,46220575:26673152,41484288,0
(1,11:4736287,4736287:0,0,0
)
[1,11:8799519,46220575:22609920,40435712,0
(1,4:8799519,8865055:22609920,454820,7208
g1,4:31409439,8865055
)
]
]
!1426
}1
Input:7:
!18
Postamble:
"""


def _write_synctex_gz(content: str) -> Path:
    """Persist a SyncTeX string to a temporary .synctex.gz file."""
    tmp = Path(tempfile.mkdtemp()) / "test.synctex.gz"
    with gzip.open(tmp, "wt", encoding="utf-8") as fp:
        fp.write(content)
    return tmp


class TestSyncTeXBox(unittest.TestCase):
    """Behaviour of the SyncTeXBox dataclass."""

    def test_contains_inside(self):
        box = _M.SyncTeXBox(
            page=1, file_id=1, line=10,
            x=0, y=1000, w=2000, h=500, d=100,
        )
        # A point centred horizontally and vertically inside the box.
        self.assertTrue(box.contains(1, sp_x=1000, sp_y=900))

    def test_contains_outside_page(self):
        box = _M.SyncTeXBox(
            page=1, file_id=1, line=10,
            x=0, y=1000, w=2000, h=500, d=100,
        )
        self.assertFalse(box.contains(2, sp_x=1000, sp_y=900))

    def test_contains_outside_horizontal(self):
        box = _M.SyncTeXBox(
            page=1, file_id=1, line=10,
            x=0, y=1000, w=2000, h=500, d=100,
        )
        self.assertFalse(box.contains(1, sp_x=3000, sp_y=900))

    def test_contains_outside_vertical(self):
        box = _M.SyncTeXBox(
            page=1, file_id=1, line=10,
            x=0, y=1000, w=2000, h=500, d=100,
        )
        # Point below the box (y < y-h, y > y+d). y=1000-500=500 is
        # the top; y=1000+100=1100 is the bottom in SyncTeX-coords.
        self.assertFalse(box.contains(1, sp_x=1000, sp_y=400))
        self.assertFalse(box.contains(1, sp_x=1000, sp_y=1200))

    def test_area_includes_height_and_depth(self):
        box = _M.SyncTeXBox(
            page=1, file_id=1, line=10,
            x=0, y=0, w=10, h=4, d=6,
        )
        # area = w * (h + d) = 10 * 10
        self.assertEqual(box.area(), 100)


class TestSyncTeXIndex(unittest.TestCase):
    """Parsing and reverse-lookup against captured SyncTeX content."""

    def test_parses_input_directory(self):
        path = _write_synctex_gz(SAMPLE_SYNCTEX)
        idx = _M.SyncTeXIndex.from_file(path)
        self.assertEqual(
            idx._inputs[1].name, "hello.tex"
        )
        self.assertEqual(
            idx._inputs[4].name, "preamble.tex"
        )

    def test_parses_box_records(self):
        path = _write_synctex_gz(SAMPLE_SYNCTEX)
        idx = _M.SyncTeXIndex.from_file(path)
        # The sample has 3 valid [ box records on page 1 (plus some
        # ( records with zero size that get filtered out).
        self.assertTrue(len(idx._boxes) >= 2)
        for box in idx._boxes:
            self.assertEqual(box.page, 1)

    def test_reverse_lookup_inside_box_returns_file_and_line(self):
        path = _write_synctex_gz(SAMPLE_SYNCTEX)
        idx = _M.SyncTeXIndex.from_file(path)
        # PDF point (300, 600) on page 1 is well inside the
        # full-page box at file_id=1, line=11.
        result = idx.reverse_lookup(page=1, x_pt=300, y_pt=600)
        self.assertIsNotNone(result)
        path_result, line = result
        self.assertEqual(path_result.name, "hello.tex")
        self.assertEqual(line, 11)

    def test_reverse_lookup_on_nonexistent_page_returns_none(self):
        path = _write_synctex_gz(SAMPLE_SYNCTEX)
        idx = _M.SyncTeXIndex.from_file(path)
        # The sample only has page 1.
        self.assertIsNone(idx.reverse_lookup(page=99, x_pt=100, y_pt=100))

    def test_reads_plain_synctex_too(self):
        # If the file isn't gzipped, the parser falls back to plain
        # open() based on the extension.
        plain = Path(tempfile.mkdtemp()) / "test.synctex"
        plain.write_text(SAMPLE_SYNCTEX)
        idx = _M.SyncTeXIndex.from_file(plain)
        self.assertEqual(idx._inputs[1].name, "hello.tex")


class TestPointConversion(unittest.TestCase):
    """The SyncTeX scaled-points constant is right."""

    def test_sp_per_pt_constant(self):
        # 65536 sp per pt is the canonical TeX/SyncTeX scaling.
        self.assertEqual(_M.SYNCTEX_SP_PER_PT, 65536)


if __name__ == "__main__":
    unittest.main()
