"""Repository rule that fetches the pinned PDF.js distribution."""

load(
    "//latex/private:pdfjs_versions.bzl",
    "PDFJS_TARBALL",
    "PDFJS_VERSION",
)

_BUILD_FILE = """\
# Auto-generated by rules_latex's pdfjs module extension.

package(default_visibility = ["//visibility:public"])

exports_files([
    "pdf.mjs",
    "pdf.worker.mjs",
    "LICENSE",
])

# Convenience filegroup for rules that want to bundle the whole pair
# of files as runfiles in one shot.
filegroup(
    name = "all",
    srcs = [
        "pdf.mjs",
        "pdf.worker.mjs",
        "LICENSE",
    ],
)
"""

def _pdfjs_repository_impl(rctx):
    rctx.download_and_extract(
        url = PDFJS_TARBALL.url,
        sha256 = PDFJS_TARBALL.sha256,
        stripPrefix = "package",
    )

    # The npm tarball drops everything under `package/`; after the
    # stripPrefix above, the files we care about land at `build/`. We
    # symlink them up to the repo root so consumers can reference them
    # as `@rules_latex_pdfjs//:pdf.mjs` rather than the deeper path.
    for name in ("pdf.mjs", "pdf.worker.mjs"):
        src = rctx.path("build/{}".format(name))
        if not src.exists:
            fail(
                "expected file {} not found in pdfjs-dist tarball; the " +
                "upstream package layout may have changed".format(src),
            )
        rctx.symlink(src, name)

    # LICENSE comes from the top of the package/ archive after
    # stripPrefix, so it's already at the repo root.
    if not rctx.path("LICENSE").exists:
        fail("expected LICENSE file missing from pdfjs-dist tarball")

    rctx.file("BUILD.bazel", _BUILD_FILE)

pdfjs_repository = repository_rule(
    implementation = _pdfjs_repository_impl,
    doc = (
        "Downloads the pinned pdfjs-dist tarball from the npm registry " +
        "and exposes pdf.mjs / pdf.worker.mjs at the repo root. Pinned " +
        "version: " + PDFJS_VERSION + "."
    ),
)
