"""The `tectonic` module extension.

A consumer's MODULE.bazel does:

    tectonic = use_extension("@rules_latex//latex/toolchain:extensions.bzl", "tectonic")
    tectonic.toolchain()
    use_repo(tectonic, "rules_latex_tectonic_toolchains")
    register_toolchains("@rules_latex_tectonic_toolchains//:all")

For fully-hermetic, offline-capable builds, also opt into the pinned
package bundle:

    tectonic.bundle()

This produces a hub repo named `rules_latex_tectonic_toolchains` that
registers a `toolchain()` for every supported platform, plus one leaf repo
per platform that holds the downloaded tectonic binary, plus (when
`tectonic.bundle()` is requested) a single repo with the pinned bundle tar.
"""

load(
    "//latex/private:biber_versions.bzl",
    "BIBER_MODERN_RELEASES",
    "BIBER_RELEASES",
)
load(
    "//latex/private:bundles.bzl",
    "DEFAULT_BUNDLE",
)
load(
    "//latex/toolchain:repositories.bzl",
    "biber_repository",
    "biblatex_repository",
    "tectonic_bundle_repository",
    "tectonic_repository",
)

_PLATFORMS = [
    struct(
        name = "linux_x86_64",
        os = "linux",
        cpu = "x86_64",
        constraint_os = "@platforms//os:linux",
        constraint_cpu = "@platforms//cpu:x86_64",
    ),
    struct(
        name = "linux_aarch64",
        os = "linux",
        cpu = "aarch64",
        constraint_os = "@platforms//os:linux",
        constraint_cpu = "@platforms//cpu:aarch64",
    ),
    struct(
        name = "macos_x86_64",
        os = "macos",
        cpu = "x86_64",
        constraint_os = "@platforms//os:macos",
        constraint_cpu = "@platforms//cpu:x86_64",
    ),
    struct(
        name = "macos_aarch64",
        os = "macos",
        cpu = "aarch64",
        constraint_os = "@platforms//os:macos",
        constraint_cpu = "@platforms//cpu:aarch64",
    ),
    struct(
        name = "windows_x86_64",
        os = "windows",
        cpu = "x86_64",
        constraint_os = "@platforms//os:windows",
        constraint_cpu = "@platforms//cpu:x86_64",
    ),
]

_BUNDLE_REPO_NAME = "rules_latex_tectonic_bundle"
_BIBLATEX_OVERLAY_REPO_NAME = "rules_latex_biblatex_overlay"

_TOOLCHAIN_HUB_BUILD_TMPL = """\
# Auto-generated by rules_latex's tectonic module extension.
package(default_visibility = ["//visibility:public"])

{toolchains}
"""

_TOOLCHAIN_BLOCK_TMPL = """\
toolchain(
    name = "tectonic_{name}",
    exec_compatible_with = [
        "{os}",
        "{cpu}",
    ],
    target_compatible_with = [
        "{os}",
        "{cpu}",
    ],
    toolchain = "@rules_latex_tectonic_{name}//:toolchain",
    toolchain_type = "@rules_latex//latex/toolchain:toolchain_type",
)
"""

def _toolchain_hub_impl(rctx):
    blocks = []
    for p in _PLATFORMS:
        blocks.append(_TOOLCHAIN_BLOCK_TMPL.format(
            name = p.name,
            os = p.constraint_os,
            cpu = p.constraint_cpu,
        ))
    rctx.file(
        "BUILD.bazel",
        _TOOLCHAIN_HUB_BUILD_TMPL.format(toolchains = "\n".join(blocks)),
    )

_toolchain_hub_repository = repository_rule(
    implementation = _toolchain_hub_impl,
    doc = "Hub repository that registers a toolchain() per supported platform.",
)

def _tectonic_impl(module_ctx):
    # `tectonic.bundle()` opts the workspace into the pinned offline package
    # bundle. Any module declaring it triggers bundle creation; this lets
    # root and transitive modules independently request offline mode without
    # coordination. The optional url/sha256 override (root module only)
    # repoints the download at a mirror — e.g. a self-hosted R2 bucket — for
    # availability independence; unset, it uses the pinned DEFAULT_BUNDLE.
    want_bundle = False
    bundle_url = DEFAULT_BUNDLE.url
    bundle_sha256 = DEFAULT_BUNDLE.sha256
    bundle_version = DEFAULT_BUNDLE.version

    # `tectonic.toolchain(modern_biblatex = True)` opts into the
    # newer biblatex + biber 2.21 stack. Same any-module-wins
    # propagation as the bundle tag, so transitive modules can
    # independently request it.
    want_modern_biblatex = False
    for mod in module_ctx.modules:
        for t in mod.tags.bundle:
            want_bundle = True

            # Only the root module may repoint the bundle, so a transitive
            # dependency can't silently swap the package source under you.
            if mod.is_root and t.url:
                if not t.sha256:
                    fail("tectonic.bundle(url = ...) also requires " +
                         "sha256 = ... (the SHA-256 of the bundle at that URL).")
                bundle_url = t.url
                bundle_sha256 = t.sha256
                if t.version:
                    bundle_version = t.version
        for t in mod.tags.toolchain:
            if t.modern_biblatex:
                want_modern_biblatex = True

    bundle_repo = _BUNDLE_REPO_NAME if want_bundle else ""
    if want_bundle:
        tectonic_bundle_repository(
            name = _BUNDLE_REPO_NAME,
            url = bundle_url,
            sha256 = bundle_sha256,
            version = bundle_version,
        )

    biblatex_overlay_repo = ""
    if want_modern_biblatex:
        biblatex_overlay_repo = _BIBLATEX_OVERLAY_REPO_NAME
        biblatex_repository(name = _BIBLATEX_OVERLAY_REPO_NAME)

    for p in _PLATFORMS:
        # Materialise a biber repo for platforms present in the releases
        # map. Platforms without an entry get no biber, and
        # latex_document(biber = True) targets fail at analysis with a
        # pointer to the system escape hatch. See DESIGN.md §4.9.
        #
        # When modern_biblatex is on, fetch biber 2.21 instead of the
        # default 2.17; the biblatex/biber pair is version-coupled via
        # the .bcf control-file format. Both maps now cover every
        # supported platform including linux/aarch64 (the 2.17 arm64
        # binary is built from source; see biber_versions.bzl /
        # DESIGN.md §4.9).
        biber_releases = BIBER_MODERN_RELEASES if want_modern_biblatex else BIBER_RELEASES
        biber_repo = ""
        if (p.os, p.cpu) in biber_releases:
            biber_repo = "rules_latex_biber_{}".format(p.name)
            biber_repository(
                name = biber_repo,
                os = p.os,
                cpu = p.cpu,
                modern = want_modern_biblatex,
            )

        tectonic_repository(
            name = "rules_latex_tectonic_{}".format(p.name),
            os = p.os,
            cpu = p.cpu,
            bundle_repo = bundle_repo,
            biber_repo = biber_repo,
            biblatex_overlay_repo = biblatex_overlay_repo,
        )

    _toolchain_hub_repository(name = "rules_latex_tectonic_toolchains")

tectonic = module_extension(
    implementation = _tectonic_impl,
    tag_classes = {
        # `tectonic.toolchain()` registers the default toolchains. The
        # optional `modern_biblatex` attr opts into the biblatex 3.21 +
        # biber 2.21 overlay (replaces the bundle's pinned 3.17/2.17
        # stack so modern CTAN extension styles work). See DESIGN.md
        # §5 item #12 for the rationale.
        "toolchain": tag_class(attrs = {
            "modern_biblatex": attr.bool(
                doc = "If True, fetch biblatex 3.21 from CTAN + biber " +
                      "2.21 and overlay them via `-Z search-path`. " +
                      "Required for modern biblatex extension styles " +
                      "(biblatex-apa 9.x, biblatex-chicago, etc.). " +
                      "Default False keeps the bundle's stable 3.17/2.17.",
                default = False,
            ),
        }),
        # `tectonic.bundle()` opts into the pinned offline package bundle.
        # When present, every materialised toolchain points at the bundle
        # and latex_document actions run with `--bundle` + `--only-cached`,
        # making compilation fully hermetic.
        #
        # `url`/`sha256` let the ROOT module point the bundle download at a
        # mirror (e.g. a self-hosted Cloudflare R2 bucket) instead of the
        # default `data1.fullyjustified.net` CDN — for availability
        # independence or to serve a rebuilt bundle. Both must be set
        # together; omit them (the common case) to use the pinned default.
        # Only the root module may override; a transitive dep can't silently
        # repoint your bundle. See DESIGN.md §4.4.
        "bundle": tag_class(attrs = {
            "url": attr.string(
                doc = "Override URL for the bundle tar (root module only). " +
                      "Requires `sha256`. Defaults to the pinned bundle.",
            ),
            "sha256": attr.string(
                doc = "SHA-256 of the bundle at `url`. Required when `url` " +
                      "is set.",
            ),
            "version": attr.string(
                doc = "Optional human-readable version label for an " +
                      "overridden bundle (informational).",
            ),
        }),
    },
)
