"""The `tectonic` module extension.

A consumer's MODULE.bazel does:

    tectonic = use_extension("@rules_latex//latex/toolchain:extensions.bzl", "tectonic")
    tectonic.toolchain()
    use_repo(tectonic, "rules_latex_tectonic_toolchains")
    register_toolchains("@rules_latex_tectonic_toolchains//:all")

This produces a hub repo named `rules_latex_tectonic_toolchains` that
registers a `toolchain()` for every supported platform, plus one leaf repo
per platform that holds the downloaded tectonic binary.
"""

load(
    "//latex/toolchain:repositories.bzl",
    "tectonic_repository",
)

_PLATFORMS = [
    struct(
        name = "linux_x86_64",
        os = "linux",
        cpu = "x86_64",
        constraint_os = "@platforms//os:linux",
        constraint_cpu = "@platforms//cpu:x86_64",
    ),
    struct(
        name = "linux_aarch64",
        os = "linux",
        cpu = "aarch64",
        constraint_os = "@platforms//os:linux",
        constraint_cpu = "@platforms//cpu:aarch64",
    ),
    struct(
        name = "macos_x86_64",
        os = "macos",
        cpu = "x86_64",
        constraint_os = "@platforms//os:macos",
        constraint_cpu = "@platforms//cpu:x86_64",
    ),
    struct(
        name = "macos_aarch64",
        os = "macos",
        cpu = "aarch64",
        constraint_os = "@platforms//os:macos",
        constraint_cpu = "@platforms//cpu:aarch64",
    ),
]

_TOOLCHAIN_HUB_BUILD_TMPL = """\
# Auto-generated by rules_latex's tectonic module extension.
package(default_visibility = ["//visibility:public"])

{toolchains}
"""

_TOOLCHAIN_BLOCK_TMPL = """\
toolchain(
    name = "tectonic_{name}",
    exec_compatible_with = [
        "{os}",
        "{cpu}",
    ],
    target_compatible_with = [
        "{os}",
        "{cpu}",
    ],
    toolchain = "@rules_latex_tectonic_{name}//:toolchain",
    toolchain_type = "@rules_latex//latex/toolchain:toolchain_type",
)
"""

def _toolchain_hub_impl(rctx):
    blocks = []
    for p in _PLATFORMS:
        blocks.append(_TOOLCHAIN_BLOCK_TMPL.format(
            name = p.name,
            os = p.constraint_os,
            cpu = p.constraint_cpu,
        ))
    rctx.file(
        "BUILD.bazel",
        _TOOLCHAIN_HUB_BUILD_TMPL.format(toolchains = "\n".join(blocks)),
    )

_toolchain_hub_repository = repository_rule(
    implementation = _toolchain_hub_impl,
    doc = "Hub repository that registers a toolchain() per supported platform.",
)

def _tectonic_impl(_ctx):
    for p in _PLATFORMS:
        tectonic_repository(
            name = "rules_latex_tectonic_{}".format(p.name),
            os = p.os,
            cpu = p.cpu,
        )
    _toolchain_hub_repository(name = "rules_latex_tectonic_toolchains")

tectonic = module_extension(
    implementation = _tectonic_impl,
    tag_classes = {
        # `tectonic.toolchain()` is currently a no-op marker; the extension
        # always registers the default set of platforms. The tag exists so we
        # can extend the API later (e.g. version pinning, custom bundles)
        # without breaking consumers.
        "toolchain": tag_class(attrs = {}),
    },
)
