"""Repository rules that download tectonic binaries.

These are invoked by the `tectonic` module extension (see extensions.bzl) to
materialise one repository per (os, cpu) platform pair, plus an optional
bundle repository when `tectonic.bundle()` is requested.
"""

load(
    "//latex/private:bundles.bzl",
    "DEFAULT_BUNDLE",
)
load(
    "//latex/private:versions.bzl",
    "TECTONIC_RELEASES",
    "TECTONIC_VERSION",
    "tectonic_download_url",
)

_TECTONIC_BUILD_FILE = """\
# Auto-generated by rules_latex.
load("@rules_latex//latex/toolchain:toolchain.bzl", "latex_toolchain")

package(default_visibility = ["//visibility:public"])

exports_files(["{exe}"])

latex_toolchain(
    name = "toolchain",
    tectonic = ":{exe}",{bundle_kw}
)
"""

def _tectonic_repository_impl(rctx):
    spec = TECTONIC_RELEASES.get((rctx.attr.os, rctx.attr.cpu))
    if spec == None:
        fail("rules_latex has no tectonic release pinned for os={} cpu={}".format(
            rctx.attr.os,
            rctx.attr.cpu,
        ))

    url = tectonic_download_url(spec.asset, version = TECTONIC_VERSION)
    rctx.download_and_extract(
        url = url,
        sha256 = spec.sha256,
        stripPrefix = "",
    )

    exe = "tectonic.exe" if rctx.attr.os == "windows" else "tectonic"
    if not rctx.path(exe).exists:
        fail("expected {} executable not found in archive {}".format(exe, url))

    bundle_kw = (
        '\n    bundle = "@{}//:bundle",'.format(rctx.attr.bundle_repo) if rctx.attr.bundle_repo else ""
    )
    rctx.file("BUILD.bazel", _TECTONIC_BUILD_FILE.format(
        exe = exe,
        bundle_kw = bundle_kw,
    ))

tectonic_repository = repository_rule(
    implementation = _tectonic_repository_impl,
    doc = "Downloads a platform-specific tectonic binary release.",
    attrs = {
        "os": attr.string(mandatory = True, values = ["linux", "macos", "windows"]),
        "cpu": attr.string(mandatory = True, values = ["x86_64", "aarch64"]),
        "bundle_repo": attr.string(
            doc = "Optional name of a tectonic_bundle_repository whose " +
                  "`:bundle` target should be wired into the generated " +
                  "latex_toolchain. Leave empty for online mode.",
            default = "",
        ),
    },
)

_BUNDLE_BUILD_FILE = """\
# Auto-generated by rules_latex.
package(default_visibility = ["//visibility:public"])

exports_files(["bundle.tar"])

alias(
    name = "bundle",
    actual = ":bundle.tar",
)
"""

def _tectonic_bundle_repository_impl(rctx):
    # We don't extract the tar — Tectonic consumes the archive as a single
    # file via its `--bundle` flag.
    rctx.download(
        url = DEFAULT_BUNDLE.url,
        output = "bundle.tar",
        sha256 = DEFAULT_BUNDLE.sha256,
    )
    rctx.file("BUILD.bazel", _BUNDLE_BUILD_FILE)

tectonic_bundle_repository = repository_rule(
    implementation = _tectonic_bundle_repository_impl,
    doc = "Downloads the pinned tectonic offline package bundle.",
)
