"""Repository rules that download tectonic and biber binaries.

These are invoked by the `tectonic` module extension (see extensions.bzl) to
materialise one repository per (os, cpu) platform pair, plus an optional
bundle repository when `tectonic.bundle()` is requested and a biber
toolchain per platform that has an upstream binary.
"""

load(
    "//latex/private:biber_versions.bzl",
    "BIBER_MIRROR_TAG",
    "BIBER_MODERN_MIRROR_TAG",
    "BIBER_MODERN_RELEASES",
    "BIBER_RELEASES",
    "biber_download_url",
)
load(
    "//latex/private:biblatex_versions.bzl",
    "BIBLATEX_SHA256",
    "BIBLATEX_STRIP_PREFIX",
    "BIBLATEX_URL",
)
load(
    "//latex/private:bundles.bzl",
    "DEFAULT_BUNDLE",
)
load(
    "//latex/private:versions.bzl",
    "TECTONIC_RELEASES",
    "TECTONIC_VERSION",
    "tectonic_download_url",
)

_TECTONIC_BUILD_FILE = """\
# Auto-generated by rules_latex.
load("@rules_latex//latex/toolchain:toolchain.bzl", "latex_toolchain")

package(default_visibility = ["//visibility:public"])

exports_files(["{exe}"])

latex_toolchain(
    name = "toolchain",
    tectonic = ":{exe}",{bundle_kw}{biber_kw}{biblatex_overlay_kw}
)
"""

def _tectonic_repository_impl(rctx):
    spec = TECTONIC_RELEASES.get((rctx.attr.os, rctx.attr.cpu))
    if spec == None:
        fail("rules_latex has no tectonic release pinned for os={} cpu={}".format(
            rctx.attr.os,
            rctx.attr.cpu,
        ))

    url = tectonic_download_url(spec.asset, version = TECTONIC_VERSION)
    rctx.download_and_extract(
        url = url,
        sha256 = spec.sha256,
        stripPrefix = "",
    )

    exe = "tectonic.exe" if rctx.attr.os == "windows" else "tectonic"
    if not rctx.path(exe).exists:
        fail("expected {} executable not found in archive {}".format(exe, url))

    bundle_kw = (
        '\n    bundle = "@{}//:bundle",'.format(rctx.attr.bundle_repo) if rctx.attr.bundle_repo else ""
    )
    biber_kw = (
        '\n    biber = "@{}//:biber_executable",'.format(rctx.attr.biber_repo) if rctx.attr.biber_repo else ""
    )
    biblatex_overlay_kw = (
        '\n    biblatex_overlay = "@{}//:overlay_files",'.format(rctx.attr.biblatex_overlay_repo) if rctx.attr.biblatex_overlay_repo else ""
    )
    rctx.file("BUILD.bazel", _TECTONIC_BUILD_FILE.format(
        exe = exe,
        bundle_kw = bundle_kw,
        biber_kw = biber_kw,
        biblatex_overlay_kw = biblatex_overlay_kw,
    ))

tectonic_repository = repository_rule(
    implementation = _tectonic_repository_impl,
    doc = "Downloads a platform-specific tectonic binary release.",
    attrs = {
        "os": attr.string(mandatory = True, values = ["linux", "macos", "windows"]),
        "cpu": attr.string(mandatory = True, values = ["x86_64", "aarch64"]),
        "bundle_repo": attr.string(
            doc = "Optional name of a tectonic_bundle_repository whose " +
                  "`:bundle` target should be wired into the generated " +
                  "latex_toolchain. Leave empty for online mode.",
            default = "",
        ),
        "biber_repo": attr.string(
            doc = "Optional name of a biber_repository whose `:biber` " +
                  "target should be wired into the generated " +
                  "latex_toolchain. Empty when no biber binary is " +
                  "available for this platform.",
            default = "",
        ),
        "biblatex_overlay_repo": attr.string(
            doc = "Optional name of a biblatex_repository whose " +
                  "`:overlay_files` filegroup should be wired into the " +
                  "generated latex_toolchain as `biblatex_overlay`. " +
                  "Empty unless the workspace opted into modern_biblatex.",
            default = "",
        ),
    },
)

_BUNDLE_BUILD_FILE = """\
# Auto-generated by rules_latex.
package(default_visibility = ["//visibility:public"])

exports_files(["bundle.tar"])

alias(
    name = "bundle",
    actual = ":bundle.tar",
)
"""

def _tectonic_bundle_repository_impl(rctx):
    # We don't extract the tar — Tectonic consumes the archive as a single
    # file via its `--bundle` flag. url/sha256 default to the pinned
    # DEFAULT_BUNDLE but may be overridden (e.g. a self-hosted R2 mirror) by
    # the root module via tectonic.bundle(url = ..., sha256 = ...).
    rctx.download(
        url = rctx.attr.url or DEFAULT_BUNDLE.url,
        output = "bundle.tar",
        sha256 = rctx.attr.sha256 or DEFAULT_BUNDLE.sha256,
    )
    rctx.file("BUILD.bazel", _BUNDLE_BUILD_FILE)

tectonic_bundle_repository = repository_rule(
    implementation = _tectonic_bundle_repository_impl,
    doc = "Downloads the pinned (or root-overridden) tectonic offline " +
          "package bundle.",
    attrs = {
        "url": attr.string(
            doc = "Bundle tar URL; empty uses the pinned DEFAULT_BUNDLE.url.",
        ),
        "sha256": attr.string(
            doc = "SHA-256 of the bundle; empty uses DEFAULT_BUNDLE.sha256.",
        ),
        "version": attr.string(
            doc = "Informational version label for the bundle.",
        ),
    },
)

_BIBER_BUILD_FILE = """\
# Auto-generated by rules_latex.
package(default_visibility = ["//visibility:public"])

exports_files(["{exe}"])

# Stable label that the latex_toolchain rule references regardless of
# platform-specific executable filename ('biber' vs 'biber.exe').
# Using a filegroup rather than alias because some platforms (macOS,
# linux) put the executable at literally `biber`, which clashes with
# an `alias(name = "biber", ...)`.
filegroup(
    name = "biber_executable",
    srcs = ["{exe}"],
)
"""

def _biber_repository_impl(rctx):
    # Pick the version's release table + mirror tag based on the
    # opt-in flag.
    if rctx.attr.modern:
        releases = BIBER_MODERN_RELEASES
        mirror_tag = BIBER_MODERN_MIRROR_TAG
    else:
        releases = BIBER_RELEASES
        mirror_tag = BIBER_MIRROR_TAG
    spec = releases.get((rctx.attr.os, rctx.attr.cpu))
    if spec == None:
        fail("rules_latex has no biber release pinned for os={} cpu={} (modern={})".format(
            rctx.attr.os,
            rctx.attr.cpu,
            rctx.attr.modern,
        ))

    url = biber_download_url(spec.asset, mirror_tag = mirror_tag)
    rctx.download_and_extract(
        url = url,
        sha256 = spec.sha256,
        stripPrefix = "",
    )

    if not rctx.path(spec.exe).exists:
        fail("expected {} executable not found in archive {}".format(spec.exe, url))

    rctx.file("BUILD.bazel", _BIBER_BUILD_FILE.format(exe = spec.exe))

biber_repository = repository_rule(
    implementation = _biber_repository_impl,
    doc = "Downloads a platform-specific biber binary release.",
    attrs = {
        "os": attr.string(mandatory = True, values = ["linux", "macos", "windows"]),
        "cpu": attr.string(mandatory = True, values = ["x86_64", "aarch64"]),
        "modern": attr.bool(
            doc = "If True, pull biber 2.21 (paired with biblatex 3.21 " +
                  "for the modern-biblatex opt-in). Otherwise the bundle-" +
                  "compatible biber 2.17.",
            default = False,
        ),
    },
)

_BIBLATEX_BUILD_FILE = """\
# Auto-generated by rules_latex.
#
# biblatex package, fetched from CTAN for the modern-biblatex
# overlay (see DESIGN.md §5 item #12). Consumers reference the
# `:overlay_files` filegroup; the rule plumbing walks the file paths
# and emits one `-Z search-path` flag per directory in
# tools/tectonic_populate_cache.py + tools/tectonic_compile.py.

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "overlay_files",
    srcs = glob(
        [
            "latex/**/*.sty",
            "latex/**/*.bbx",
            "latex/**/*.cbx",
            "latex/**/*.lbx",
            "latex/**/*.dbx",
            "latex/**/*.def",
            "latex/**/*.cfg",
        ],
        # biblatex 3.21 ships .sty/.bbx/.cbx/.lbx/.def/.cfg but no
        # .dbx (data-model definitions live in extension packages
        # like biblatex-apa). Allow the empty pattern so the glob
        # doesn't fail at analysis on the canonical layout.
        allow_empty = True,
    ),
)
"""

def _biblatex_repository_impl(rctx):
    rctx.download_and_extract(
        url = BIBLATEX_URL,
        sha256 = BIBLATEX_SHA256,
        stripPrefix = BIBLATEX_STRIP_PREFIX,
    )
    if not rctx.path("latex/biblatex.sty").exists:
        fail(
            "biblatex archive layout changed: expected latex/biblatex.sty " +
            "inside {} (stripped {}). Check the upstream zip structure and " +
            "update BIBLATEX_STRIP_PREFIX in biblatex_versions.bzl.".format(
                BIBLATEX_URL,
                BIBLATEX_STRIP_PREFIX,
            ),
        )
    rctx.file("BUILD.bazel", _BIBLATEX_BUILD_FILE)

biblatex_repository = repository_rule(
    implementation = _biblatex_repository_impl,
    doc = "Downloads the pinned biblatex package source from CTAN. " +
          "Used by the `modern_biblatex` opt-in to overlay a newer " +
          "biblatex than the bundle ships.",
)
