#!/usr/bin/env python3
"""Generate the bundle-resident package manifest from the tectonic bundle.

The CTAN auto-resolver in ``tectonic_populate_cache.py`` consults this
manifest to decide whether a ``\\RequirePackage`` reference is already
provided by the tectonic bundle. References resolvable from the bundle
are *not* fetched from CTAN, which avoids the version-coupling
disasters that come from shadowing bundle packages (e.g. biblatex 3.18+
fetched on top of the bundle's biber 2.17 — see DESIGN.md §4.10).

This tool is invoked manually by a maintainer (a) when first
generating the manifest and (b) any time tectonic's pinned bundle
version is bumped (see DESIGN.md §5 open question #4).

Output is a sorted, deduplicated list of ``.sty``/``.cls`` basenames
(without extensions), one per line, written to
``latex/toolchain/bundle_manifest.txt`` by default. ~80 KB of
diff-friendly text; ~6,000 entries for the current
``tlextras-2022.0r0`` bundle.

Usage:
    python3 tools/extract_bundle_manifest.py --tectonic <path> [--output <path>]
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path


# Match ``.sty`` and ``.cls``. We deliberately do not include ``.def``
# or ``.cfg`` files: tectonic's resolver uses kpathsea, but
# ``\RequirePackage{X}`` / ``\usepackage{X}`` look up ``X.sty``
# specifically. Documents that do ``\input{X.def}`` directly are rare
# in practice and the scanner doesn't pick those up either.
_PACKAGE_FILE_RE = re.compile(r"^(.+)\.(sty|cls)$")


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--tectonic",
        type=Path,
        required=True,
        help="Path to the tectonic binary. The toolchain-resolved "
             "tectonic from a populated bazel workspace lives under "
             "$(bazel info output_base)/external/+tectonic+rules_latex_tectonic_*",
    )
    p.add_argument(
        "--output",
        type=Path,
        default=Path("latex/toolchain/bundle_manifest.txt"),
        help="Where to write the manifest. Default is the canonical "
             "path under latex/toolchain/.",
    )
    p.add_argument(
        "--cache-dir",
        type=Path,
        default=None,
        help="TECTONIC_CACHE_DIR override. Defaults to a fresh "
             "tempdir so we don't pollute the user's real cache.",
    )
    return p.parse_args()


def enumerate_bundle(tectonic: Path, cache_dir: Path) -> list[str]:
    """Run ``tectonic -X bundle search ''`` and return every entry."""
    env = os.environ.copy()
    env["TECTONIC_CACHE_DIR"] = str(cache_dir.resolve())
    # Search with an empty term to list every file in the bundle. The
    # first invocation downloads the bundle (~50 MB) into cache_dir;
    # subsequent invocations reuse it.
    print(
        f"Enumerating tectonic bundle (cache: {cache_dir})...",
        file=sys.stderr,
    )
    result = subprocess.run(
        [str(tectonic), "-X", "bundle", "search", ""],
        env=env,
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.splitlines()


def extract_package_names(filenames: list[str]) -> set[str]:
    """Filter to .sty/.cls and strip extensions to get package names."""
    names: set[str] = set()
    for line in filenames:
        line = line.strip()
        m = _PACKAGE_FILE_RE.match(line)
        if m:
            names.add(m.group(1))
    return names


def write_manifest(names: set[str], output: Path) -> None:
    """Write the manifest with a stable, diff-friendly format."""
    output.parent.mkdir(parents=True, exist_ok=True)
    sorted_names = sorted(names)
    with output.open("w") as fp:
        # Header line — comment so the file can be loaded with simple
        # "skip lines starting with #" parsing. Includes a hint about
        # how the file was generated.
        fp.write(
            "# Bundle-resident package manifest for the tectonic\n"
            "# bundle. Generated by tools/extract_bundle_manifest.py.\n"
            "# Refresh when tectonic's pinned bundle version changes.\n"
            "# See DESIGN.md §5 item #12 for the role this plays in\n"
            "# CTAN auto-resolution.\n"
        )
        for name in sorted_names:
            fp.write(name + "\n")
    print(
        f"Wrote {len(sorted_names)} entries to {output}",
        file=sys.stderr,
    )


def main() -> int:
    args = parse_args()
    if not args.tectonic.is_file():
        print(
            f"error: tectonic binary not found at {args.tectonic}",
            file=sys.stderr,
        )
        return 1

    cache_owned: tempfile.TemporaryDirectory[str] | None = None
    cache_dir = args.cache_dir
    if cache_dir is None:
        cache_owned = tempfile.TemporaryDirectory(prefix="rules_latex_manifest_")
        cache_dir = Path(cache_owned.name)
    try:
        filenames = enumerate_bundle(args.tectonic, cache_dir)
        names = extract_package_names(filenames)
        write_manifest(names, args.output)
    finally:
        if cache_owned is not None:
            cache_owned.cleanup()
    return 0


if __name__ == "__main__":
    sys.exit(main())
